<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">

    <link href="/static/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/static/css/style.css?v=4.1.0" rel="stylesheet">

</head>
<body>
<?php $this->view->partial("nav");?>

  <div class="walletadmin-content">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                  <div class="page-title">发送道具</div>
                  <div class="addadmin">



                      <div class="wrapper wrapper-content animated fadeInRight">
                          <div class="row">
                              <div class="col-sm-12">
                                  <div class="ibox float-e-margins">
                                      <div class="ibox-tools">
                                          <a class="collapse-link">
                                              <i class="fa fa-chevron-up"></i>
                                          </a>
                                          <a class="dropdown-toggle" data-toggle="dropdown" href="form_basic.html#">
                                              <i class="fa fa-wrench"></i>
                                          </a>
                                          <ul class="dropdown-menu dropdown-user">
                                              <li><a href="form_basic.html#">选项1</a>
                                              </li>
                                              <li><a href="form_basic.html#">选项2</a>
                                              </li>
                                          </ul>
                                          <a class="close-link">
                                              <i class="fa fa-times"></i>
                                          </a>
                                      </div>
                                      <div class="ibox-content">
                                          <form class="form-horizontal m-t">
                                              <div class="form-group">
                                                  <label class="col-sm-1 control-label">游戏区服：</label>
                                                  <div class="col-sm-4">
                                                      <select class="form-control zone" name="zone"  multiple="multiple">
                                                      </select>
                                                  </div>
                                                  <div class="col-sm-6 zoneList"></div>
                                              </div>
                                              <div class="form-group">
                                                  <label class="col-sm-1 control-label">角色名</label>
                                                  <div class="col-sm-4">
                                                      <input class="form-control" name="nickname" placeholder="多角色名间以@分隔,不填默认发全服">
                                                      </input>
                                                  </div>
                                              </div>
                                              <div class="form-group">
                                                  <label class="col-sm-1 control-label">邮件标题：</label>
                                                  <div class="col-sm-4">
                                                      <input class="form-control" name="mailtitle">
                                                      </input>
                                                  </div>
                                              </div>
                                              <div class="form-group">
                                                  <label class="col-sm-1 control-label">邮件内容：</label>
                                                  <div class="col-sm-4">
                                                      <input class="form-control" name="mailcontent">
                                                      </input>
                                                  </div>
                                              </div>

                                              <div class="form-group">
                                                  <label class="col-sm-1 control-label">已选道具列表：</label>
                                                  <div class="col-sm-4">
                                                      <select class="form-control itemSelected" name="itemSelected[]" multiple="multiple">
                                                      </select>
                                                  </div>
                                                  <label class="col-sm-1 control-label">道具列表：</label>
                                                  <div class="col-sm-4">
                                                      <select class="form-control itemList">

                                                      </select>
                                                      <input type="text" class="form-control itemNum" value="" placeholder="请输入数量">
                                                      <button type="button" class="form-control text-danger itemAdd">添加道具到已选列表</button>
                                                  </div>
                                              </div>

                                              <div class="form-group">
                                                  <label class="col-sm-1 control-label"></label>
                                                  <div class="col-sm-4">
                                                      <button type="button" class=" send w-btn">发送</button>
                                                  </div>
                                              </div>

                                              <div class="form-group" style="text-align: right; margin-right: 15px;">
                                                  <button type="button" class="btn btn-w-m btn-white send">发送</button>
                                                  <button type="button" class=" send w-btn">发送</button>
                                              </div>
                                          </form>
                                      </div>
                                  </div>
                              </div>
                          </div>

                  </div>
              </div>
          </div>
      </div>
  </div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>

<script src="/static/js/jquery.min.js?v=2.1.4"></script>
<script src="/static/js/content.js?v=1.0.0"></script>
<script src="/static/js/config.js"></script>
<script src="/static/js/common.js"></script>

<script type="text/javascript">
          jQuery.support.cors = true;
          $(function(){
              var zoneValList = [];

              url = "http://" + RemoteAddr + ":" + Port + "/gm/getitemlist";
              var item;
              $.ajax({
                  url: url,
                  type: "GET",
                  dataType:"json",
                  async: false,
                  success: function(data){
                      //On ajax success do this
                      console.info("success.");
                      console.log(data["success"]);
                      if (data["success"] == true){
                          delete(data["success"])
                          // console.log(data);
                          // alert("Settings is Ok. The Machine is rebooting.");
                          $.each(data, function(idx,val){
                              item += "<option value="+idx+">"+idx+" "+val;
                              // console.log(idx, val)
                              item += "</option>";
                          });
                          $(".itemList").html(item);
                          $(".itemList").chosen();
                      }else{
                          return;
                      }
                  },
                  error: function(xhr, ajaxOptions, thrownError) {
                      //On error do this
                      console.info("error.");
                      // if (xhr.status == 200) {
                      //     alert(ajaxOptions);
                      // } else {
                      //     alert(xhr.status);
                      //     alert(thrownError);
                      // }
                      // window.location.href = "500.html";
                  }
              });

              // $(".itemList").chosen();

              // 添加道具
              $(".itemAdd").click(function(){
                  if(!$(".itemNum").val()){
                      layer.tips('亲，请输入道具数量哦~', ".itemNum");
                      return;
                  }
                  var value = $(".itemList").val() + "," + $(".itemNum").val();
                  var itemName = $(".itemList").find("option:selected").text();
                  itemName = itemName.substr( itemName.indexOf("-") + 1, itemName.length).replace( ' ', '');
                  $(".itemSelected").append("<option value='" + value + "'>" + itemName + " — " + $(".itemNum").val() + "个" + " </option>");
              });

              // 追加道具
              $(".itemAppend").click(function(){
                  if($(".lastItem option").size() <= 0){
                      return;
                  }
                  $(".lastItem option").each(function(){
                      $(".itemSelected").append("<option value='" + $(this).val() + "'>" + $(this).text() + "</option>");
                      $(this).remove();
                  });
              });

              // 删除已选道具
              $(".itemSelected").dblclick(function(){
                  $(".itemSelected option[value='" + $(this).val() + "']").remove();
              });

              // submit
              $(".send").click(function(){

                  if(!$("input[name='mailtitle']").val() || !$("input[name='mailcontent']").val() || !$("select[name='itemSelected[]']").text()){
                      //tips层
                      layer.tips('亲，有必填参数未填写哦~', ".send");
                      return;
                  }

                  url = "http://" + RemoteAddr + ":" + Port +  "/manager/senditem";

                  $.ajax({
                      url: url,
                      type: "POST",
                      data: getParams(),
                      // contentType: "application/json",
                      dataType:"json",
                      success: function(data){
                          //On ajax success do this
                          console.info("success.");
                          if (data["success"]){
                              alert("发送成功");
                          }else{
                              alert("发送失败");
                              console.log("fail");
                              return;
                          }

                      },
                      error: function(xhr, ajaxOptions, thrownError) {
                          //On error do this
                          console.info("error.");
                          console.log(xhr);
                          if (xhr.status == 200) {
                              alert(ajaxOptions);
                          } else {
                              alert(xhr.status);
                              alert(thrownError);
                          }
                      }
                  });
              });

              $(".zone").change(function(){
                  showZone();
              });

              function showZone(){
                  zoneValList = [];
                  var zoneNameList = [];
                  $(".zone option:selected").each(function(){
                      zoneNameList.push($(this).text());
                      zoneValList.push($(this).val());
                  });
                  $(".zoneList").text(zoneNameList.join(","));
              }

              $(".channel").change(function(){
                  showChan();
              });





              // 获取参数
              function getParams(){
                  var itemStr = "";
                  $(".itemSelected option").each(function(){
                      itemStr += $(this).val() + ";";
                  });
                  return {
                      zones: zoneValList.join("|"),
                      nickname: $("input[name='nickname']").val(),
                      mailtitle: $("input[name='mailtitle']").val(),
                      mailcontent: $("input[name='mailcontent']").val(),
                      itemstr : itemStr.substring(0, itemStr.length - 1)
                  }
              }
          })
      </script>

<!--<script>-->
<!--  $(document).ready(function(){-->
<!--    $.fn.adminAdd({})-->
<!--  });-->
<!---->
<!--  $("#eye").click(function() {-->
<!--      if($(".password").attr("type") == "text") {-->
<!--          $(".password").attr("type", "password");-->
<!--          $("#eye span").removeClass("icon-yanjing_kai");-->
<!--          $("#eye span").addClass("icon-yanjing_bi");-->
<!--      } else {-->
<!--          $(".password").attr("type", "text");-->
<!--          $("#eye span").removeClass("icon-yanjing_bi");-->
<!--          $("#eye span").addClass("icon-yanjing_kai");-->
<!---->
<!--      }-->
<!--  });-->
<!--</script>-->
</body>
</html>