<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">

</head>
<body>
<?php $this->view->partial("nav");?>

  <div class="walletadmin-content">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                  <div class="page-title">添加管理员</div>
                  <div class="addadmin">

                      <form action="/admin/addAdmin"  method="post" enctype="multipart/form-data">
                      <div class="addadmin-account">
                        <div class="addadmin-left">
                            <span>*</span><span>账户名</span>
                        </div>
                        <div class="addadmin-right">
                            <input type="text" name="admin_name">
                        </div>
                      </div>
                      <div class="addadmin-pwd">
                          <div class="addadmin-left">
                              <span>*</span><span>真实姓名</span>
                          </div>
                          <div class="addadmin-right">
                              <input type="text" autocomplete="off" name="real_name">
                          </div>
                      </div>
                      <div class="addadmin-pwd">
                          <div class="addadmin-left">
                            <span>*</span><span>密&nbsp;&nbsp;&nbsp;码</span>
                          </div>
                          <div class="addadmin-right">
                              <input type="password" autocomplete="new-password" name="password" class="password" placeholder="请设置包含英文及数字的8～16位字符密码">
                              <a id="eye" title="点击隐藏或显示密码" style="position:relative;right:50px;opacity: 1;">
                                  <span class="iconfont icon-yanjing_bi"></span>
                              </a>
                          </div>
                      </div>
                      <div class="addadmin-phone">
                          <div class="addadmin-left">
                            <span>*</span><span>手机号</span>
                          </div>
                          <div class="addadmin-right">
                              <input type="text" name="phone">
                          </div>
                      </div>
                      <div class="addadmin-root">
                          <div class="addadmin-left">
                            <span>*</span><span>是否为超级管理员</span>
                          </div>
                          <div class="addadmin-right">
                              <input type="radio" name="is_super" value="1" id="is-root"><label for="is-root">是</label>
                              <input type="radio" name="is_super" value="0" id="no-root" checked><label for="no-root">否</label>
                          </div>
                      </div>
                          <input type="submit" value="提交" class="w-btn">
                      </form>

                  </div>
              </div>
          </div>
      </div>
  </div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>
<script>
  $(document).ready(function(){
    $.fn.adminAdd({})
  });

  $("#eye").click(function() {
      if($(".password").attr("type") == "text") {
          $(".password").attr("type", "password");
          $("#eye span").removeClass("icon-yanjing_kai");
          $("#eye span").addClass("icon-yanjing_bi");
      } else {
          $(".password").attr("type", "text");
          $("#eye span").removeClass("icon-yanjing_bi");
          $("#eye span").addClass("icon-yanjing_kai");

      }
  });
</script>
</body>
</html>