<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
<!--    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">-->
<!--    <link rel="stylesheet" href="/static/css/theme-wallet.css">-->
<!--    <link rel="stylesheet" href="/static/css/iconfont.css">-->
    <link rel="stylesheet" href="/static/css/chat-bootstrap.min.css">

</head>
<body>

<style>
    #webim {
        background-color: #3E4B5E ;
    }

    #webim .user-list {
        height:500px;
        margin: 0;
        padding:0;
        border-right:1px solid #d6e9c6;
        overflow-y:auto;
    }

    #webim .user-list .user-item {
        height: 60px;
        line-height: 60px;
        overflow: hidden;
        padding: 5px;
        cursor: pointer;
    }


    #webim  .user-list .user-item:hover {
        background-color: #bce8f1;
        opacity: 0.8;
    }

    #webim .avatar {
        width:50px;
        height:50px;
        float:left;
    }

    #webim .user-name {
        line-height: 60px;
        padding-left:5px;
        float:left;
        color:#08967F;
    }

    .no-padding
    {
        padding:0;
    }
    #webim .chat-list {
        height:399px;
        overflow-y:auto;
    }

    #webim  .chat-list .msg-item {
        padding: 5px;
    }

    #webim  .chat-list  .notice {
        color:#08967F;
        font-size:12px;
        padding: 10px 0;
    }

    #webim  .chat-list .msg-item .msg {
        background: #d9edf7;
        line-height:25px;
        float:left;
        margin-left:10px;
        border-radius: 5px;
        padding: 0px 5px;
    }

    #webim .username {
        float:left;
        color:#08967F;
    }


    #webim .message {
        height:100px;
        border-top:1px solid #d6e9c6;
    }

    #webim .message .text {
        width:80%;
        float:left;
        height:100px;
    }

    #webim .message .text textarea {
        width:100%;
        height:100%;
        border: none;
        outline: none;
        padding: 10px;
    }

    #webim .message .send {
        width:20%;
        float:left;
        text-align: center;
        line-height:100px;
        color: #08967F;
        border-left:1px solid #d6e9c6;
        cursor: pointer;
    }
</style>

<?php //$this->view->partial("nav");?>

  <div class="walletadmin-content" id="webim">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">

                  <div class="panel panel-info " >
                      <div class="panel-heading">
                          moell/webim: PHP + Swoole 简易聊天室
                      </div>
                      <div class="panel-body no-padding">
                          <div class="col-xs-3 user-list">

                          </div>
                          <div class="col-xs-9 no-padding">
                              <div class="chat-list">

                              </div>
                              <div class="message" id="send">
<!--                                  <input id="send" type="text" placeholder="别憋着，说点啥~~ 回车既发射"></input>-->
                                  <div class="text">
                                      <textarea></textarea>
                                  </div>
                                  <div class="send" >
                                      发送
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>

                  </div>
              </div>
          </div>
      </div>
  </div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<!--<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>-->
<!--<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>-->
<script type="text/javascript" src="/static/js/chat-push.js"></script>
<script type="text/javascript" src="/static/js/chat.js"></script>
<!--<script type="text/javascript" src="/static/js/webim.js"></script>-->
<script type="text/javascript" src="/static/js/chart-jquery.min.js"></script>
<script>
    $(function(){

        $(".message .send").click(function(){
            var url = '/admin/chat/send';
            var data = {'content':text, 'game_id':1};

            $.post(url,data,function(result){
                //todo
                $(this).val('');
            },'json');



            var text = $(".message .text textarea");
            var msg = text.val();
            var account = "<?= $admin['account'] ?>";

            if ($.trim(msg) == '') {
                this.layerErrorMsg('请输入消息内容');
                return false;
            }

            // this.data.wsServer.send(msg);

            var html = '<div class="col-xs-10 col-xs-offset-2 msg-item ">'
                +'<div class="col-xs-1 no-padding pull-right">'
                +'<div class="avatar">'
                +'<img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1579087727938&di=7154a64b5e4a93fd9b47ec538bbea201&imgtype=0&src=http%3A%2F%2Fimage.biaobaiju.com%2Fuploads%2F20180803%2F23%2F1533308847-sJINRfclxg.jpeg" width="50" height="50" class="img-circle">'
                +'</div>'
                +'</div>'

                +'<div class="col-xs-11">'
                +'<div class="col-xs-12">'
                +'<div class="username pull-right">'+account+'</div>'
                +'<div>'
                +'<div class="col-xs-12 no-padding">'
                +'<div class="msg pull-right">'+msg+'</div>'
                +'</div>'
                +'</div>';

            $('.chat-list').append(html);

//            this.appendUser(this.data.info.name, this.data.info.avatr, this.data.info.fd);
//            this.scrollBottom();

            text.val('');
        });

    });
</script>
</body>
</html>