<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title></title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>
<body>
    <?php $this->view->partial("nav");?>
    <div class="walletadmin-content">
      <div class="walletadmin-box walletadmin-list">
          <div class="box">

              <div class="container">
                  <div class="page-title">添加区服</div>
                  <div class="addadmin">

                      <form action="/admin/diserver/add"  method="post" enctype="multipart/form-data">

                          <div class="addadmin-root">
                              <div class="addadmin-left">
                                  <span>*</span><span>服务器名</span>
                              </div>
                              <div class="addadmin-right">
                                  <?php foreach ($data['server_list'] as $k => $v){ ?>
                                      <input type="radio" name="server_id" value="<?= $v['id'] ?>" id="<?= $v['id'] ?>" <?php if($k == 0){ echo 'checked'; } ?> ><label for="<?= $v['id'] ?>"><?= $v['server_name'] ?></label> &nbsp;
                                  <?php } ?>
                              </div>
                          </div>

                          <div class="addadmin-pwd">
                              <div class="addadmin-left">
                                  <span>*</span><span>区服id</span>
                              </div>
                              <div class="addadmin-right">
                                  <input type="text" autocomplete="off" name="diserver_id">
                              </div>
                          </div>

                          <div class="addadmin-pwd">
                              <div class="addadmin-left">
                                  <span>*</span><span>区服名</span>
                              </div>
                              <div class="addadmin-right">
                                  <input type="text" autocomplete="off" name="diserver_name">
                              </div>
                          </div>

                  </div>
                  <input type="submit" value="提交" class="w-btn">
                  </form>

              </div>

              <div class="container">

                  <div class="search-ui">
                      <form action="/admin/diserver/list" method="get">

                          <div class="search-ui-input">
                              <div>
                                  <input type="text" class="input-primary" placeholder="服务器名称" name="server_name" value="">
                              </div>
                              <div>
                                  <button class='btn btn-primary'>搜索</button>
                              </div>
                          </div>
                      </form>
                  </div>

<!--                  <div class="page-title">服务器列表</div>-->
                  <div class="table">
                      <table>
                        <thead>
                            <tr>
                                <th>服务器名</th>
                                <th>区服名</th>
                                <th>区服id</th>
                                <th>创建时间</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>

                        <?php foreach($list as $v){ ?>
                                <tr>
                                    <td><?php echo $v['server_name'];?></td>
                                    <td><?php echo $v['diserver_id'];?></td>
                                    <td><?php echo $v['diserver_name'];?></td>
                                    <td><?php echo date('Y-m-d H:i:s',$v['created_at']); ?><span>
                                    </td>
                                    <td>
                                        <a href="/admin/diserver/del?id=<?php echo $v['id']; ?>" onclick="javascript:return confirm('是否确认删除？');"><button class="action-btn disabled">删除</button></a>
<!--                                        <a href="/admin/channel/list?id=--><?php //echo $v['id']; ?><!--"><button class="action-btn noicon">渠道列表</button></a>-->
                                    </td>
                                </tr>
                        <?php } ?>

                        
                        </tbody>
                      </table>
                      <div class="pagination-box">

                          <?php
                          if($list){
                              //存储页码字符串
                              $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                              //当前页码数，默认当前页码为1
                              $curPage = isset($_GET['page'])?$_GET['page']:1;
                              if($curPage <=5){
                                  $begin =1;
                                  $end = $data['totalpage']>=10?10:$data['totalpage'];
                              }else{
                                  $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                                  $begin =$end -9<=1?1:$end -9;
                              }
                              //实现上一页
                              $prev = $data['page'] -1<=1?1:$data['page'] -1;
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                              //根据起始页与终止页将当前页面的页码显示出来
                              for($i=$begin;$i<=$end;$i++){
                                  //使用if实现高亮显示当前点击的页码
                                  if($data['page'] == $i){
                                      $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                  }else{
                                      $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                  }
                              }


                              //实现下一页
                              $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                              $pageNumString .='</div>';
                              echo $pageNumString;
                          }
                          
                          ?>
                          
                      </div>
                          
                  </div>
              </div>
          </div>
      </div>
  </div>

<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
</body>
</html>