<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>新贝区块链支付解决方案</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">

</head>
<body>
<?php $this->view->partial("nav");?>

  <div class="walletadmin-content">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                  <div class="page-title">编辑管理员</div>
                  <div class="addadmin">
                      <form action="/<?php echo $pro_no; ?>/admin/info"  method="post" enctype="multipart/form-data">
                      <div class="addadmin-account">
                        <div class="addadmin-left">
                            <span>*</span><span>账户名</span>
                        </div>
                        <div class="addadmin-right">
                            <input type="text" name="admin_name" value="<?php echo $admin['admin_name'] ?>">
                        </div>
                      </div>
                      <div class="addadmin-pwd">
                          <div class="addadmin-left">
                              <span>*</span><span>真实姓名</span>
                          </div>
                          <div class="addadmin-right">
                              <input type="text" name="real_name" value="<?php echo $admin['real_name'] ?>">
                          </div>
                      </div>
                      <div class="addadmin-pwd">
                          <div class="addadmin-left">
                            <span>*</span><span>密&nbsp;&nbsp;&nbsp;码</span>
                          </div>
                          <div class="addadmin-right">
                              <input type="password" name="password" class="password">
                              <a id="eye" title="点击隐藏或显示密码" style="position:relative;right:50px;opacity: 1;">
                                  <span class="iconfont icon-yanjing_bi"></span>
                              </a>
                          </div>
                      </div>
                      <div class="addadmin-phone">
                          <div class="addadmin-left">
                            <span>*</span><span>手机号</span>
                          </div>
                          <div class="addadmin-right">
                              <input type="text" name="phone" value="<?php echo $admin['phone'] ?>">
                          </div>
                      </div>
                      <div class="addadmin-root">
                          <div class="addadmin-left">
                            <span>*</span><span>是否全权管理员</span>
                          </div>
                          <div class="addadmin-right">
                              <input type="radio" name="is_power" value="1" id="is-root" <?php if($admin['is_power'] == 1) echo "checked"?> ><label for="is-root"  >是</label>
                              <input type="radio" name="is_power" value="0" id="no-root" <?php if($admin['is_power'] == 0) echo "checked"?> ><label for="no-root" >否</label>
                          </div>
                      </div>
                      <div class="addadmin-permissions">
                          <div class="addadmin-left">
                            <span>*</span><span>分配权限</span>
                          </div>
                          <div class="choose-permissions" id="choose-permissions">
                              <?php
                              if($permission){
                                  for ($i = 0;$i < count($permission[0]);$i++){
                              ?>
                              <div class="per-item">
                                <table>
                                    <thead>
                                    <tr>
                                        <th width="20%"><?php echo $permission[0][$i]['show_name']; ?></th>
                                        <th width="80%">
                                            <input type="checkbox" id="admin-man-<?php echo $i; ?>">
                                            <label for="admin-man-<?php echo $i; ?>">全选</label>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                <?php
//                                var_dump($permission[$permission[0][$i]['id']]);
                                    $first = $permission[0][$i]['id'];
                                    for($j = 0;$j < count($permission[$first]);$j++){
                                ?>
                                    <tr>
                                        <td><?php echo $permission[$first][$j]['show_name']; ?></td>
                                        <td>
                                            <?php
//                                            var_dump($permission[$permission[0][$i]['id']][$j]['id']);
                                            $second = $permission[$first][$j]['id'];
                                            for($z = 0;$z < count($permission[$second]);$z++){ ?>
                                                <input class="<?php if(strpos($permission[$second][$z]['name'],'_do')!=false){ echo "do"; }else{ echo "read"; } ?>" type="checkbox" id='admin-list-watch-<?php echo $permission[$second][$z]['id']; ?>' name="permissions[]" value="<?php echo $permission[$second][$z]['name'];?>"
                                                <?php
                                                    if(strpos($admin['permissions'],','.$permission[$second][$z]['name'].',') !== false){
                                                        echo "checked";
                                                    }
                                                    ?>
                                                >
                                                <label for='admin-list-watch-<?php echo $permission[$second][$z]['id']; ?>'><?php echo $permission[$second][$z]['show_name'];  ?></label>
                                            <?php } ?>
                                        </td>
                                    </tr>
                              <?php } } }?>
                                    </tbody>
                                </table>
                            </div>
                          </div>  
                      </div>
                          <input type="hidden" name="id" value="<?php echo $admin['id'];  ?>">
                          <input type="submit" value="提交" class="w-btn">
                      </form>

                  </div>
              </div>
          </div>
      </div>
  </div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>
<script>
  $(document).ready(function(){
    $.fn.adminInfo({})
  });

  $("#eye").click(function() {
      if($(".password").attr("type") == "text") {
          $(".password").attr("type", "password");
          $("#eye span").removeClass("icon-yanjing_kai");
          $("#eye span").addClass("icon-yanjing_bi");
      } else {
          $(".password").attr("type", "text");
          $("#eye span").removeClass("icon-yanjing_bi");
          $("#eye span").addClass("icon-yanjing_kai");

      }
  });
</script>
</body>
</html>