<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title></title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>
<body>
    <?php $this->view->partial("nav");?>
    <div class="walletadmin-content">
      <div class="walletadmin-box walletadmin-list">
          <div class="box">
              <div class="container">
                  <div class="page-title">管理员列表</div>
                  <div class="table">
                      <table>
                        <thead>
                            <tr>
                                <th width="15%">账户名</th>
                                <th width="15%">真实姓名</th>
                                <th width="15%">角色</th>
                                <th width="20%">电话号码</th>
                                <th width="10%">状态</th>
                                <th width="30%">操作</th>
                            </tr>
                        </thead>
                        <tbody>

                        <?php foreach($list as $v){ ?>
                                <tr>
                                    <td><?php echo $v['admin_name'];?></td>
                                    <td><?php echo $v['real_name'];?></td>
                                    <td>
                                        <?php
                                            switch ($v['role']){
                                                case 'developers':
                                                    echo '开发商';
                                                    break;
                                                case 'operators':
                                                    echo '运维';
                                                    break;
                                                case 'service':
                                                    echo '普通账号';
                                                    break;
                                                case 'commissioner':
                                                    echo '专员';
                                                    break;
                                                case 'supper':
                                                    echo '超级管理员';
                                                    break;
                                                default:
                                                    echo '';
                                                    break;
                                            }
                                        ?>
                                    </td>
                                    <td><?php echo $v['phone'];?></td>
                                    <td>
                                        <span>
                                            <?php
                                            if($v['status']==1) {
                                               echo  "正常";
                                            }elseif($v['status'] == 0){
                                                echo "已禁用";
                                            }
                                            ?>
                                        <span>
                                    </td>
                                    <td>
                                        <a href="/admin/updateStatus?id=<?php echo $v['id']; ?>&status=0" onclick="javascript:return confirm('是否禁用？');"><button class="action-btn disabled">禁用</button></a>
                                        <a href="/admin/updateStatus?id=<?php echo $v['id']; ?>&status=1" onclick="javascript:return confirm('是否启用？');"><button class="action-btn open">启用</button></a>
                                        <a href="/admin/update?id=<?php echo $v['id']; ?>&status=1"><button class="action-btn">编辑</button></a>
                                        <a href="/admin/updateStatus?id=<?php echo $v['id']; ?>&status=-1"><button class="action-btn disabled">删除</button></a>
                                    </td>
                                </tr>
                        <?php } ?>

                        
                        </tbody>
                      </table>
                      <div class="pagination-box">

                          <?php
                          if($list){
                              //存储页码字符串
                              $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                              //当前页码数，默认当前页码为1
                              $curPage = isset($_GET['page'])?$_GET['page']:1;
                              if($curPage <=5){
                                  $begin =1;
                                  $end = $data['totalpage']>=10?10:$data['totalpage'];
                              }else{
                                  $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                                  $begin =$end -9<=1?1:$end -9;
                              }
                              //实现上一页
                              $prev = $data['page'] -1<=1?1:$data['page'] -1;
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                              //根据起始页与终止页将当前页面的页码显示出来
                              for($i=$begin;$i<=$end;$i++){
                                  //使用if实现高亮显示当前点击的页码
                                  if($data['page'] == $i){
                                      $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                  }else{
                                      $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                  }
                              }


                              //实现下一页
                              $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                              $pageNumString .='</div>';
                              echo $pageNumString;
                          }
                          
                          ?>
                          
                      </div>
                          
                  </div>
              </div>
          </div>
      </div>
  </div>

<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
</body>
</html>