
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>
<body>
<?php $this->view->partial("nav");?>
  <div class="walletadmin-content" id='wallet-type-detail'>
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                <div class="page-title"><a href="/<?php echo $pro_no; ?>/admin/log">日志管理</a>  <span>>> 详情</span></div>
                  <div class="log-detail-desc">
                        <p>
                          操作员：<?php echo $info['admin_name']; ?>
                        </p>
                        <p>
                          日志标题：<?php echo $info['log_title']; ?>
                        </p>
                        <p>
                          IP地址：<?php echo $info['ip']; ?>
                        </p>
                        <p>
                          操作时间：<?php echo date('Y-m-d,H:i:s',$info['created_at']); ?>
                        </p>
                        <p>
                          表名：<?php echo $info['table']; ?>
                        </p>
                        <p>
                          操作类型：<?php echo $info['sql_type']; ?>
                        </p>
                        <p>
                          操作内容：<?php echo $info['sql']; ?>
                        </p>
                  </div>
              </div>
          </div>
      </div>
  </div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
</body>
</html>