<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">

</head>
<body>
<?php $this->view->partial("nav");?>

  <div class="walletadmin-content">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">

                  <div class="page-title">添加订单（导入csv格式）【最近更新时间: <?= $data['order']['created_at'] ?>】</div>
                  <div class="addadmin">

                      <form action="/admin/orderAdd"  method="post" enctype="multipart/form-data">
                          <div class="addadmin-account">
                            <div class="addadmin-left">
                                <span>*</span><span>文件</span>
                            </div>
                              <input type="file" name="file">
                          </div>

                          </div>
<!--                            <input type="submit" class="btn btn-primary" value="发放" onclick="javascript:return confirm('分发后，自动分发糖果，是否进行分发？');">-->
                          <input type="submit" value="导入" class="w-btn">
                      </form>
                  </div>

              <div class="container">
                  <div class="search-ui">
                      <form action="/admin/orderadd/excle" method="get">

                          <div class="search-ui-input">
                              <div>
                                  <input type="text" class="input-primary" placeholder="订单id/昵称" name="search" value="">
                              </div>
                              <div>
                                  <button class='btn btn-primary'>搜索</button>
                              </div>
                          </div>
                      </form>
                  </div>
              </div>

              <div class="container">
                  <div class="page-title">全服订单列表【总订单量：<?= $data['allcount'] ?>】</div>
                  <div class="table">
                      <table>
                          <thead>
                          <tr>
                              <th width="15%">订单id</th>
                              <th width="15%">昵称</th>
                              <th width="10%">渠道</th>
                              <th width="15%">数量</th>
                              <th width="15%">道具</th>
                              <th width="15%">商品id</th>
                              <th width="15%">下单时间</th>
                          </tr>
                          </thead>
                          <tbody>

                          <?php foreach($list as $v){ ?>
                              <tr>
                                  <td><?= $v['orderId'];?></td>
                                  <td><?= $v['NickName'];?></td>
                                  <td><?= $v['Channel'];?></td>
                                  <td><?= $v['Amount'];?></td>
                                  <td><?= $v['Items'];?></td>
                                  <td><?= $v['GoodsId'];?></td>
                                  <td><?= date('Y-m-d H:i:s',$v['CreateTime']);?></td>
                              </tr>
                          <?php } ?>


                          </tbody>
                      </table>
                      <div class="pagination-box">

                          <?php
                          if($list){
                              //存储页码字符串
                              $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                              //当前页码数，默认当前页码为1
                              $curPage = isset($_GET['page'])?$_GET['page']:1;
                              if($curPage <=5){
                                  $begin =1;
                                  $end = $data['totalpage']>=10?10:$data['totalpage'];
                              }else{
                                  $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                                  $begin =$end -9<=1?1:$end -9;
                              }
                              //实现上一页
                              $prev = $data['page'] -1<=1?1:$data['page'] -1;
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                              //根据起始页与终止页将当前页面的页码显示出来
                              for($i=$begin;$i<=$end;$i++){
                                  //使用if实现高亮显示当前点击的页码
                                  if($data['page'] == $i){
                                      $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                  }else{
                                      $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                  }
                              }


                              //实现下一页
                              $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                              $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                              $pageNumString .='</div>';
                              echo $pageNumString;
                          }

                          ?>

                      </div>

                  </div>
              </div>

          </div>
      </div>
  </div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>
<script>
  $(document).ready(function(){
    $.fn.adminAdd({})
  });

  $("#eye").click(function() {
      if($(".password").attr("type") == "text") {
          $(".password").attr("type", "password");
          $("#eye span").removeClass("icon-yanjing_kai");
          $("#eye span").addClass("icon-yanjing_bi");
      } else {
          $(".password").attr("type", "text");
          $("#eye span").removeClass("icon-yanjing_bi");
          $("#eye span").addClass("icon-yanjing_kai");

      }
  });
</script>
</body>
</html>