<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">

</head>
<body>
<?php $this->view->partial("nav");?>

  <div class="walletadmin-content">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                  <a href="/admin/list"><button class='btn btn-primary'> &nbsp 返回列表 &nbsp </button></a>
                  <br>
                  <br>
                  <div class="page-title">编辑管理员</div>
                  <div class="addadmin">

                      <form action="/admin/update"  method="post" enctype="multipart/form-data">
                          <div class="addadmin-account">
                            <div class="addadmin-left">
                                <span>*</span><span>账户名</span>
                            </div>
                            <div class="addadmin-right">
                                <input type="text" name="admin_name" value="<?= $data['admin']['admin_name'] ?>">
                            </div>
                          </div>
                          <div class="addadmin-pwd">
                              <div class="addadmin-left">
                                  <span>*</span><span>真实姓名</span>
                              </div>
                              <div class="addadmin-right">
                                  <input type="text" autocomplete="off" name="real_name" value="<?= $data['admin']['real_name'] ?>">
                              </div>
                          </div>
                          <div class="addadmin-pwd">
                              <div class="addadmin-left">
                                <span>*</span><span>密&nbsp;&nbsp;&nbsp;码</span>
                              </div>
                              <div class="addadmin-right">
                                  <input type="password" autocomplete="new-password" name="password" class="password" placeholder="不填即不修改">
                                  <a id="eye" title="点击隐藏或显示密码" style="position:relative;right:50px;opacity: 1;">
                                      <span class="iconfont icon-yanjing_bi"></span>
                                  </a>
                              </div>
                          </div>
                          <div class="addadmin-phone">
                              <div class="addadmin-left">
                                <span>*</span><span>手机号</span>
                              </div>
                              <div class="addadmin-right">
                                  <input type="text" name="phone" value="<?= $data['admin']['phone'] ?>">
                              </div>
                          </div>
                          <div class="addadmin-root">
                              <div class="addadmin-left">
                                <span>*</span><span>角色</span>
                              </div>
                              <div class="addadmin-right">
                                  <input type="radio" name="role" value="supper" id="supper" <?php if($data['admin']['role'] == 'supper'){ echo 'checked'; } ?> ><label for="supper">超级管理员</label> &nbsp;
                                  <input type="radio" name="role" value="developers" id="developers" <?php if($data['admin']['role'] == 'developers'){ echo 'checked'; } ?> ><label for="developers">开发商</label> &nbsp;
                                  <input type="radio" name="role" value="operators" id="operators" <?php if($data['admin']['role'] == 'operators'){ echo 'checked'; } ?> ><label for="operators">运维</label> &nbsp;
                                  <input type="radio" name="role" value="service" id="service" <?php if($data['admin']['role'] == 'service'){ echo 'checked'; } ?> ><label for="service">普通账户</label> &nbsp;
                                  <input type="radio" name="role" value="commissioner" id="commissioner" <?php if($data['admin']['role'] == 'commissioner'){ echo 'checked'; } ?> ><label for="commissioner">专员</label> &nbsp;
                              </div>
                          </div>
                          </div>
                        <input type="hidden" value="<?= $data['admin']['id'] ?>" name='id'>
                        <input type="submit" value="提交" class="w-btn">
                      </form>

                  </div>
              </div>
          </div>
      </div>
  </div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>
<script>
  $(document).ready(function(){
    $.fn.adminAdd({})
  });

  $("#eye").click(function() {
      if($(".password").attr("type") == "text") {
          $(".password").attr("type", "password");
          $("#eye span").removeClass("icon-yanjing_kai");
          $("#eye span").addClass("icon-yanjing_bi");
      } else {
          $(".password").attr("type", "text");
          $("#eye span").removeClass("icon-yanjing_bi");
          $("#eye span").addClass("icon-yanjing_kai");

      }
  });
</script>
</body>
</html>