<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/datepicker.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">
</head>
<body>
    <?php $this->view->partial("nav");?>
    <div class="walletadmin-content">
      <div class="walletadmin-box walletadmin-list">
          <div class="box">
              <div class="container">
                  <div class="page-title">区服列表</div>
                  <div class="table">
                      <table>
                        <thead>
                            <tr>
                                <th width="15%">区服名</th>
                                <th width="15%">状态</th>
                            </tr>
                        </thead>
                        <tbody>

                        <?php foreach($list as $v){ ?>
                                <tr>
                                    <td><?php echo $v['ServerName'];?></td>
                                    <td>
                                        <span>
                                            <?php
                                            if($v['ServerStatus'] == 1) {
                                               echo  "正常";
                                            }elseif($v['ServerStatus'] == 0){
                                                echo "维护中";
                                            }
                                            ?>
                                        <span>
                                    </td>
                                </tr>
                        <?php } ?>

                        
                        </tbody>
                      </table>
                          
                  </div>
              </div>
          </div>
      </div>
  </div>

    <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="/static/js/moment.min.js"></script>
    <script type="text/javascript" src="/static/js/datepicker.all.js"></script>
    <script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
    <script>
        $(document).ready(function(){
            chooseTime()
        })
    </script>
</body>
</html>