<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>新贝区块链支付解决方案</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">
</head>
<body>
<?php $this->view->partial("nav"); ?>
  <div class="walletadmin-content" id="generation-wallet">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                <div class="page-title">生成钱包地址</div>
                <div class="generation-wallet-content">
                    <div>
                        <select name='chain_id' class='admin-select chain_id' id="select-chain-symbol" onchange="nulsNotice()">";
                            <?php foreach ($chains as $chain) { ?>
                                <option name='chain_id' class="chain_id" value='<?php echo $chain['id'].','.$chain['chain_symbol'];?>' ><?php echo $chain['chain_symbol'];?></option>
                            <?php } ?>
                        </select>
                      <input type="text" placeholder="请输入数量(1~500)" name="count" class="add-wallet-count">
                    </div>
                    <div>
                        <input type="password" placeholder="密码一" name="password1" class="add-wallet-password1">
                        <a id="yanjing1"  style="position:relative;right:25px;top:15px;opacity: 1;" title="点击隐藏或显示密码">
                            <span class="iconfont icon-yanjing_bi"></span>
                        </a>

                        <input type="password" placeholder="密码二" name="password2" class="add-wallet-password2">
                        <a id="yanjing2"  style="position:relative;right:25px;top:15px;opacity: 1;" title="点击隐藏或显示密码">
                            <span class="iconfont icon-yanjing_bi"></span>
                        </a>

                        <input type="password" placeholder="密码三" name="password3" class="add-wallet-password3">
                        <a id="yanjing3"  style="position:relative;right:25px;top:15px;opacity: 1;" title="点击隐藏或显示密码">
                            <span class="iconfont icon-yanjing_bi"></span>
                        </a>
                    </div>

                    <div id="nuls-notice">
                    </div>


                    <div class="pwd-warn">
                      <input type="text" placeholder="请输入密码提示" name="password_prompt" class="password_prompt">
                    </div>

                    <div><i class="icon icon-mark"></i><span style="color: red;">   密码用于保护私钥和交易授权，强度非常重要。本系统不储存密码，也无法帮您找回，请务必牢记。</span></div>

                    <div id="showloading" style="text-align:center;padding:20px;display: none;"><img src="/static/images/loading.gif" style="width:30px;vertical-align:middle;"> 请稍候......</div>

                    <div class="generation-wallet-submit" id="hide-loading">
                        <input type="hidden" name="pro_no" id="pro_no" value="<?php echo $pro_no; ?>">
                        <button class="btn btn-primary" onclick="addUserWallet()">生成</button>
                    </div>
                </div>
              </div>
          </div>
      </div>
  </div>
<div class="dialog" id='wallet-generate-suc'>
    <div class="wrapper">
        <div class="generate-suc-padding">
            <p>生成钱包地址成功</p >
            <p>批次号：<span></span></p >
            <a href="/<?php echo $pro_no; ?>/walletaddressbatch/list"><button class="w-btn">确定</button></a>
        </div>
    </div>
</div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script>
    $("#yanjing1").click(function() {
        if($(".add-wallet-password1").attr("type") == "text") {
            $(".add-wallet-password1").attr("type", "password");
            $("#yanjing1 span").removeClass("icon-yanjing_kai");
            $("#yanjing1 span").addClass("icon-yanjing_bi");
        } else {
            $(".add-wallet-password1").attr("type", "text");
            $("#yanjing1 span").removeClass("icon-yanjing_bi");
            $("#yanjing1 span").addClass("icon-yanjing_kai");

        }
    });

    $("#yanjing2").click(function() {
        if($(".add-wallet-password2").attr("type") == "text") {
            $(".add-wallet-password2").attr("type", "password");
            $("#yanjing2 span").removeClass("icon-yanjing_kai");
            $("#yanjing2 span").addClass("icon-yanjing_bi");
        } else {
            $(".add-wallet-password2").attr("type", "text");
            $("#yanjing2 span").removeClass("icon-yanjing_bi");
            $("#yanjing2 span").addClass("icon-yanjing_kai");

        }
    });

    $("#yanjing3").click(function() {
        if($(".add-wallet-password3").attr("type") == "text") {
            $(".add-wallet-password3").attr("type", "password");
            $("#yanjing3 span").removeClass("icon-yanjing_kai");
            $("#yanjing3 span").addClass("icon-yanjing_bi");
        } else {
            $(".add-wallet-password3").attr("type", "text");
            $("#yanjing3 span").removeClass("icon-yanjing_bi");
            $("#yanjing3 span").addClass("icon-yanjing_kai");

        }
    });

    function nulsNotice(){
        var select = $("#select-chain-symbol").find("option:selected").html();
        if(select === 'NULS'){
            $("#nuls-notice").html('                        <i class="icon icon-mark"></i><span style="color: red;">   三段密码的长度相加为8~20位,并且密码只能由数字和小写英文组成,请按此操作。</span>\n');
        }else{
            $("#nuls-notice").html('                        <i class="icon icon-mark"></i><span style="color: red;">   单段密码请设置8~16位中英文字符。</span>\n');
        }
    }

    nulsNotice();

</script>
</body>
</html>