<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>新贝区块链支付解决方案</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>

<body>
<?php $this->view->partial("nav");?>
    <div class="walletadmin-content" id="wallet-list-detail">
        <div class="walletadmin-box">
            <div class="box">
                <div class="container">
                    <form action="" method="get">
                        <div class="list-detail-sort">
                          <div>
                              <select name="coin_id" id="" class="admin-select">
                                  <option value="" name="coin_id" <?php if($data['coin_id'] == ""){echo "selected";} ?>>全部</option>
                                  <?php foreach($data['coin'] as $item){ ?>
                                      <option name="coin_id" value="<?php echo $item['id']; ?>"  <?php if($data['coin_id'] == $item['id']){echo "selected";} ?>><?php echo $item['coin_symbol'];?></option>
                                  <?php } ?>
                              </select>
                            <input type="text" class="input-primary sort-wallet-address" placeholder="钱包地址或标签" name="address" value="<?php echo $data['address']; ?>">
                          </div>
                          <div>
                              <input type="hidden" name="chain_id" value="<?php echo $data['chain_id']; ?>">
                              <input type="hidden" name="batch_no" value="<?php echo $data['batch_no']; ?>">
                              <button class='btn btn-primary'>搜索</button>
                          </div>
                        </div>
                    </form>
                </div>
                <div class="container list-detail-table">
                    <div class="list-detail-title">
                        <div class="page-title sub-title">
                            <a href="/<?php echo $pro_no; ?>/walletaddressbatch/list">钱包列表</a>
                            <span>>><?php echo $data['batch_no']; ?> 批次详情</span>&nbsp;&nbsp;
                            <span><?php echo $data['coin_symbol']; ?>约合:<?php echo $data['allamount']; ?></span>
                        </div>
<!--                        <div class="list-detail-report">-->
<!--                            <button class="btn btn-primary">导出keysotry</button>-->
<!--                        </div>-->
                    </div>
                   
                    <div class="table">
                        <table>
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>地址</th>
                                    <th>数据库金额</th>
                                    <th>链上金额</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach($list as $v){ ?>
                                <tr>
                                    <td><?php echo $v['id'];?></td>
                                    <td><?php echo $v['address'];?></td>
                                    <td><?php echo $v['coin_balance'];?></td>
                                    <td><?php echo $v['coin_balance_update'];?></td>
                                    <td>
                                        <button class="action-btn" ><a href='/<?php echo $pro_no; ?>/walletasset/confirm?id=<?php echo $v['id']; ?>'>确认金额</a></button>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                        <div class="pagination-box">
                            <?php
                            if($list){
                                //存储页码字符串
                                $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                                //当前页码数，默认当前页码为1
                                $curPage = isset($_GET['page'])?$_GET['page']:1;
                                if($curPage <=5){
                                    $begin =1;
                                    $end = $data['totalpage']>=10?10:$data['totalpage'];
                                }else{
                                    $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                                    $begin =$end -9<=1?1:$end -9;
                                }
                                //实现上一页
                                $prev = $data['page'] -1<=1?1:$data['page'] -1;
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                                //根据起始页与终止页将当前页面的页码显示出来
                                for($i=$begin;$i<=$end;$i++){
                                    //使用if实现高亮显示当前点击的页码
                                    if($data['page'] == $i){
                                        $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                    }else{
                                        $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                    }
                                }


                                //实现下一页
                                $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                                $pageNumString .='</div>';
                                echo $pageNumString;
                            }

                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
</body>

</html>