<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>新贝区块链支付解决方案</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/datepicker.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">
</head>

<body>
<?php $this->view->partial("nav"); ?>
    <div class="walletadmin-content" id='wallet-list'>
        <div class="walletadmin-box">
            <div class="box">
                <div class="container">
                  <div class="search-ui">
                      <form action="" method="get">
                        <div>
                            <select name="chain_id"  class="admin-select">
                                <option name="chain_id" value="" <?php if($data['chain_id'] == ""){echo "selected";} ?>>全部</option>
                                <?php foreach($data['chain'] as $item){ ?>
                                    <option name="chain_id" value="<?php echo $item['id']; ?>"  <?php if($data['chain_id'] == $item['id']){echo "selected";} ?>><?php echo $item['chain_symbol'];?></option>
                                <?php } ?>
                            </select>

                            <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                <input type="text" autocomplete="off" name="begin_date" placeholder="开始时间" class="c-datepicker-data-input only-date" <?php if(isset($data['begin_date'])){ if($data['begin_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['begin_date'])."'"; }} ?>>
                            </div>
                            <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                <input type="text" autocomplete="off" name="end_date" placeholder="结束时间" class="c-datepicker-data-input only-date" <?php if(isset($data['end_date'])){ if($data['end_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['end_date'])."'"; }} ?>>
                            </div>
                            <select name="admin_no"  class="admin-select">
                                <option name="admin_no" value="" <?php if($data['admin_no'] == ""){echo "selected";} ?>>全部</option>
                                <?php foreach($data['admin'] as $item){ ?>
                                    <option name="admin_no" value ="<?php echo $item['admin_no'] ?>" <?php if($data['admin_no'] == $item['admin_no']){echo "selected";} ?>><?php echo $item['admin_name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="search-ui-input">
                            <div>
                                <input type="text" class="input-primary" name="batch_no" placeholder="批次号" value="<?php echo $data['batch_no'] ?>">
                                <input type="text" class="input-primary" placeholder="钱包地址或标签" name="address" value="<?php echo $data['address']; ?>">

                            </div>
                            <div>
                                <button class='btn btn-primary'>搜索</button>
                            </div>
                        </div>
                      </form>
                  </div>
                </div>
                <div class="container list-table-content">
                    <div class="page-title">
                        钱包列表
                        <a href="/<?php echo $pro_no; ?>/walletaddress/transferList"><button class="action-btn noicon" style="float: right">转出历史</button></a>
                    </div>
                    <div class="table">
                        <table>
                            <thead>
                                <tr>
                                    <th>批次号</th>
                                    <th>类型</th>
                                    <th>数量</th>
                                    <th>操作员</th>
                                    <th>创建时间</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach($list as $v){ ?>
                                <tr>
                                    <td><?php echo $v['batch_no'];?></td>
                                    <td class="chain_symbol"><?php echo $v['chain_symbol'];?></td>
                                    <td><?php echo $v['address_total'];?></td>
                                    <td><?php echo $v['admin_name'];?></td>
                                    <td><?php echo date('Y-m-d,H:i:s',$v['created_at'])?></td>
                                    <td>
                                        <a href='/<?php echo $pro_no; ?>/walletaddress/list?batch_no=<?php echo $v['batch_no'];?>&chain_id=<?php echo $v['chain_id']; ?>&address=<?php echo $data['address'] ?>'><button class="action-btn" >详情</button></a>
                                        <?php if(strpos($data['permission'],',wallet_list_do,') != false || $data['is_super'] == 1 || $data['is_power'] == 1){ ?>
                                            <button class="action-btn show-cold-dialog" value="<?php echo $v['id'];?>"><span style="display: none;"><?php echo $v['password_prompt']; ?></span>转出冷钱包</button>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                        <div class="pagination-box">
                            <?php
                            if($list){
                                //存储页码字符串
                                $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                                //当前页码数，默认当前页码为1
                                $curPage = isset($_GET['page'])?$_GET['page']:1;
                                if($curPage <=5){
                                    $begin =1;
                                    $end = $data['totalpage']>=10?10:$data['totalpage'];
                                }else{
                                    $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                                    $begin =$end -9<=1?1:$end -9;
                                }
                                //实现上一页
                                $prev = $data['page'] -1<=1?1:$data['page'] -1;
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                                //根据起始页与终止页将当前页面的页码显示出来
                                for($i=$begin;$i<=$end;$i++){
                                    //使用if实现高亮显示当前点击的页码
                                    if($data['page'] == $i){
                                        $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                    }else{
                                        $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                    }
                                }


                                //实现下一页
                                $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                                $pageNumString .='</div>';
                                echo $pageNumString;
                            }

                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<div class="dialog" id="roll-out-cold">
    <div class="wrapper">
        <form action="/<?php echo $pro_no; ?>/walletaddress/transferColdWallet" method="post" enctype="multipart/form-data">
            <div class="dialog-title">
                请输入密码
            </div>
            <div class="out-cold-pwd">
                <input type="hidden" id="current-out-id" name="batch_id">
                <input type="hidden" id="chain_symbol" name="chain_symbol">
                <input type="password" class="input-primary" placeholder="密码一" name="password1">
                <input type="password" class="input-primary ui-margin" placeholder="密码二" name="password2">
                <input type="password" class="input-primary" placeholder="密码三" name="password3">
                <div class="cl"></div>
            </div>
            <div class="out-cold-prompt">
                密码提示:
                <span id="out-cold-prompt-text"></span>
            </div>
            <div id="eos_show" style="display: none">
                <div class="dialog-title" >
                    请输入出账钱包密码
                </div>
                <div class="out-cold-pwd">
                    <input type="password" style="width: 650px;" class="input-primary" placeholder="请输入出账钱包密码" name="transferwallet_password">
                    <div class="cl"></div>
                </div>
            </div>

            <div class="out-cold-confirm">
                <button class="w-btn">
                    提交
                </button>
            </div>
        </form>
    </div>
</div>

<div class="dialog">
    <span id="pro_no"><?php echo $pro_no; ?></span>
    <span id="eos_address"><?php if(isset($EOSAddress)){echo $EOSAddress;} ?></span>
    <span id="enough_resource"><?php echo $enough_resource; ?></span>
</div>

<div class="message">
    <div class="message_title"></div>
</div>

<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/moment.min.js"></script>
<script type="text/javascript" src="/static/js/datepicker.all.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script>
    $(document).ready(function(){
        chooseTime()
    })
</script>

</body>
</html>