<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>新贝区块链支付解决方案</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/datepicker.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">
</head>

<body>
<?php $this->view->partial("nav");?>
    <div class="walletadmin-content" id="out-manage">
        <div class="walletadmin-box">
            <div class="box">
                <form action="" method="get">
                    <div class="container out-manage-sort">
                        <div class="manage-sort-left">
                            <select name="coin_id" id="coin_id" class="admin-select">
                                <?php foreach($data['coin'] as $item){ ?>
                                    <option name="coin_id" value="<?php echo $item['id']; ?>"  <?php if($data['coin_id'] == $item['id']){echo "selected";} ?>><?php echo $item['coin_symbol'];?></option>
                                <?php } ?>
                            </select>
                            <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                <input type="text" autocomplete="off" name="begin_date" placeholder="开始时间" class="c-datepicker-data-input only-date" <?php if(isset($data['begin_date'])){ if($data['begin_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['begin_date'])."'"; }} ?>>
                            </div>
                            <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                <input type="text" autocomplete="off" name="end_date" placeholder="结束时间" class="c-datepicker-data-input only-date" <?php if(isset($data['end_date'])){ if($data['end_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['end_date'])."'"; }} ?>>
                            </div>
                            <input type="text" class="input-primary sort-wallet-address" placeholder="钱包地址或标签" name="address" value="<?php echo $data['address']; ?>">
                        </div>
                        <div class="manage-sort-right">
                            <button class="btn btn-primary">搜索</button>
                        </div>
                    </div>
                </form>
                <div class="container out-manage-total-box">
                    <div class="out-manage-total">
                        <span>出账钱包地址：<?php if($data['transferWallet']){echo $data['transferWallet']['transferWallet'];} ?></span>
                        <span><?php echo $data['coin_symbol']; ?>余额：<?php if($data['transferWallet']['coinAsset']){echo $data['transferWallet']['coinAsset'];}else{echo '0';} ?></span>
                        <span><?php echo $data['chain_symbol']; ?>余额：<?php if($data['transferWallet']['feeAsset']){echo $data['transferWallet']['feeAsset'];}else{echo '0';} ?></span>
                    </div>
                </div>
                <div class="container out-manage-content">
                    <div class="page-title">
                      提币失败 
                    </div>
                    <div class="pagr-title-right">
                        <div class="out-coin-total">
                                <?php echo $data['coin_symbol']; ?>约合:<?php if($data['allamount']){echo $data['allamount'];}else{echo 0;} ?>
                        </div>
                            <?php if(strpos($data['permission'],',withdraw_fail_do,') != false || $data['is_super'] == 1 || $data['is_power'] == 1){ ?>
                                <div class="out-coin-action">
                                   <button class='btn btn-primary' id='batch-mention-money'>批量重转</button>
                                    <a href="/<?php echo $pro_no; ?>/withdraw/failwithdrawExcel?coin_id=<?php echo $data['coin_id'] ?>&address=<?php echo $data['address'] ?>&begin_date=<?php echo $data['begin_date'] ?>&end_date=<?php echo $data['end_date'] ?>"><button class='btn btn-primary'>导出Excel</button></a>
                                </div>
                            <?php } ?>
                    </div>
                    <div class="table">
                        <table>
                            <thead>
                                <tr>
                                    <th width="5%">
                                        
                                    </th>
                                    <th>
                                        钱包地址
                                    </th>
                                    <th>
                                        金额
                                    </th>
                                    <?php if($data['coin_symbol'] == 'EOS'){  ?>
                                        <th>
                                            标签
                                        </th>
                                    <?php } ?>
                                    <th>
                                        失败时间
                                    </th>
                                    <th>
                                        失败原因
                                    </th>
                                    <th>
                                        操作
                                    </th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach($list as $v){ ?>
                                <tr>
                                    <td>
                                        <input type="checkbox" id="b-<?php echo $v['id'];?>" value="<?php echo $v['id'];?>"><label for="b-<?php echo $v['id'];?>"></label>
                                    </td>
                                    <td><?php echo $v['address'];?></td>
                                    <td><?php echo $v['coin_amount'];?></td>
                                    <?php if($data['coin_symbol'] == 'EOS'){  ?>
                                        <td><?php echo $v['memo'];?></td>
                                    <?php } ?>
                                    <td><?php echo date('Y-m-d,H:i:s',$v['updated_at']);?></td>
                                    <td><?php echo $v['remark'];?></td>
                                    <td>
                                        <?php if(strpos($data['permission'],',withdraw_fail_do,') != false || $data['is_super'] == 1 || $data['is_power'] == 1){ ?>
                                            <button class="action-btn noicon out-manage-deal-fail" value="<?php echo $v['id']; ?>">失败重转</button>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                        <div class="manage-select-all">
                            <input type="checkbox" id='all-checkbox'><label for="all-checkbox"></label>
                            <span class="all-text">全选</span>
                            <span class="select-all-total">已选金额汇总：<a id='select-all-total'>0.00</a></span>
                        </div>

                        <div id="showloading" style="text-align:center;position:absolute;top:500px;left:700px;display: none;z-index:100"><img src="/static/images/loading.gif" style="width:30px;vertical-align:middle;"> 请稍候......</div>


                        <div class="pagination-box">
                            <?php
                            if($list){
                                //存储页码字符串
                                $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                                //当前页码数，默认当前页码为1
                                $curPage = isset($_GET['page'])?$_GET['page']:1;
                                if($curPage <=5){
                                    $begin =1;
                                    $end = $data['totalpage']>=10?10:$data['totalpage'];
                                }else{
                                    $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                                    $begin =$end -9<=1?1:$end -9;
                                }
                                //实现上一页
                                $prev = $data['page'] -1<=1?1:$data['page'] -1;
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                                //根据起始页与终止页将当前页面的页码显示出来
                                for($i=$begin;$i<=$end;$i++){
                                    //使用if实现高亮显示当前点击的页码
                                    if($data['page'] == $i){
                                        $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                    }else{
                                        $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                    }
                                }


                                //实现下一页
                                $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                                $pageNumString .='</div>';
                                echo $pageNumString;
                            }

                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="dialog" id="out-wallet-pwd-dialog-select">
            
            <div class="wrapper">
              <form action="/<?php echo $pro_no; ?>/withdraw/dealMoreOrders" method="post" enctype="multipart/form-data">
                <div class="dialog-title">
                    请输入出账钱包密码
                </div>
                <p><?php echo $data['coin_symbol']; ?>提币金额汇总：<span>10<span></p >
                <div class="out-wallet-pwd-dialog-input">
                    <input type="password" class="input-primary" name="password" placeholder="请输入密码">
                    <input type="hidden" name="id" id="select-ok-id" value="">
                    <input type="hidden" name="coin_id"  value="<?php echo $data['coin_id']; ?>">
                </div>
                <div class="out-wallet-pwd-dialog-btn">
                    <button class="w-btn" onclick="loadingMore()">提交</button>
                </div>
              </form>
            </div>
            
        </div>
        <div class="dialog" id="fail-out-wallet-pwd-dialog">
                <div class="wrapper">
                  <form action="/<?php echo $pro_no; ?>/withdraw/success" method="post" enctype="multipart/form-data">
                    <div class="dialog-title">
                        请输入出账钱包密码
                    </div>
                    <p><?php echo $data['coin_symbol']; ?>提币金额汇总：<span>10<span></p >
                    <div class="out-wallet-pwd-dialog-input">
                        <input type="password" class="input-primary" name="password" placeholder="请输入密码">
                        <input type="hidden" name="id" id="ok-id" value="">
                    </div>
                    <div class="out-wallet-pwd-dialog-btn">
                        <button class="w-btn" onclick="loading()">提交</button>
                    </div>
                  </form>
                </div>  
        </div>

        <div class="dialog">
            <span id="pro_no"><?php echo $pro_no; ?></span>
            <span id="eos_address"><?php if(isset($EOSAddress)){echo $EOSAddress;} ?></span>
            <span id="enough_resource"><?php echo $enough_resource; ?></span>
        </div>

        <div class="message">
            <div class="message_title"></div>
        </div>
        <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
        <script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>
        <script type="text/javascript" src="/static/js/moment.min.js"></script>
        <script type="text/javascript" src="/static/js/datepicker.all.js"></script>
        <script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
        <script>
            $(document).ready(function(){
                $.fn.chooseTime({});
                $.fn.withdrawDealing();
            });
            function loading(){
                $("#fail-out-wallet-pwd-dialog").css("display","none");
                $("#showloading").css("display","block");
            }

            function loadingMore(){
                $("#out-wallet-pwd-dialog-select").css("display","none");
                $("#showloading").css("display","block");
            }

        </script>
</body>

</html>