<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/datepicker.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">
</head>

<body>
<?php $this->view->partial("nav");?>
    <div class="walletadmin-content" id="withdrawal">
        <div class="walletadmin-box">
            <div class="box">
                <div class="container">
                    <form action="" method="get">
                        <div class="search-ui">
                            <div>
                                <select name="coin_id" id="" class="admin-select">
                                    <?php foreach($data['coin'] as $item){ ?>
                                        <option name="coin_id" value="<?php echo $item['id']; ?>"  <?php if($data['coin_id'] == $item['id']){echo "selected";} ?>><?php echo $item['coin_symbol'];?></option>
                                    <?php } ?>
                                </select>
                                <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                    <input type="text" autocomplete="off" name="begin_date" placeholder="开始时间" class="c-datepicker-data-input only-date" <?php if(isset($data['begin_date'])){ if($data['begin_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['begin_date'])."'"; }} ?>>
                                </div>
                                <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                    <input type="text" autocomplete="off" name="end_date" placeholder="结束时间" class="c-datepicker-data-input only-date" <?php if(isset($data['end_date'])){ if($data['end_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['end_date'])."'"; }} ?>>
                                </div>
                                <select name="admin_no" id="" class="admin-select">
                                    <option name="admin_no" value="" <?php if($data['admin_no'] == ""){echo "selected";} ?> >操作员</option>
                                    <?php foreach($data['admin'] as $item){ ?>
                                        <option name="admin_no" value ="<?php echo $item['admin_no'] ?>" <?php if($data['admin_no'] == $item['admin_no']){echo "selected";} ?>><?php echo $item['admin_name'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="search-ui-input">
                                <div>
<!--                                    <input type="text" class="input-primary" placeholder="Hash" name="hash" value="--><?php //echo $data['hash']; ?><!--">-->
                                    <input type="text" class="input-primary" placeholder="钱包地址或标签" name="address" value="<?php echo $data['address']; ?>">
                                </div>
                                <div>
                                    <button class='btn btn-primary'>搜索</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="container withdrawal-content">
                    <div class="page-title">
                            已到账
                    </div>
                     <div class="pagr-title-right">   
                        <div class="out-coin-total">
                            
                                <?php echo $data['coin_symbol']; ?>约合:<?php if($data['allamount']){echo $data['allamount'];}else{echo 0;} ?>
                            
                        </div>
                        <?php if(strpos($data['permission'],',withdraw_success_do,') != false || $data['is_super'] == 1 || $data['is_power'] == 1){ ?>
                            <div class="out-coin-action">
                                <a href="/<?php echo $pro_no; ?>/withdraw/successwithdrawExcel?coin_id=<?php echo $data['coin_id'] ?>&address=<?php echo $data['address'] ?>&begin_date=<?php echo $data['begin_date'] ?>&end_date=<?php echo $data['end_date'] ?>"><button class='btn btn-primary'>导出Excel</button></a>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="table">
                        <table>
                            <thead>
                                <tr>
                                    <th>金额</th>
                                    <th>钱包地址</th>
                                    <?php if($data['coin_symbol'] == 'EOS'){  ?>
                                        <th>
                                            标签
                                        </th>
                                    <?php } ?>
                                    <th>操作员</th>
                                    <th>操作时间</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach($list as $v){ ?>
                                <tr>
                                    <td><?php echo $v['coin_amount'];?></td>
                                    <td><?php echo $v['address'];?></td>
                                    <?php if($data['coin_symbol'] == 'EOS'){  ?>
                                        <td><?php echo $v['memo'];?></td>
                                    <?php } ?>
                                    <td><?php echo $v['admin_name'];?></td>
                                    <td><?php echo date('Y-m-d,H:i:s',$v['updated_at']);?></td>
                                    <td>
                                        <a href='/<?php echo $pro_no; ?>/walletflow/list?obj_id=<?php echo $v['id']; ?>&coin_id=<?php echo $v['coin_id']; ?>'><button class="action-btn" >详情</button></a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                        <div class="pagination-box">
                            <?php
                            if($list){
                                //存储页码字符串
                                $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                                //当前页码数，默认当前页码为1
                                $curPage = isset($_GET['page'])?$_GET['page']:1;
                                if($curPage <=5){
                                    $begin =1;
                                    $end = $data['totalpage']>=10?10:$data['totalpage'];
                                }else{
                                    $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                                    $begin =$end -9<=1?1:$end -9;
                                }
                                //实现上一页
                                $prev = $data['page'] -1<=1?1:$data['page'] -1;
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                                //根据起始页与终止页将当前页面的页码显示出来
                                for($i=$begin;$i<=$end;$i++){
                                    //使用if实现高亮显示当前点击的页码
                                    if($data['page'] == $i){
                                        $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                    }else{
                                        $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                    }
                                }


                                //实现下一页
                                $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                                $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                                $pageNumString .='</div>';
                                echo $pageNumString;
                            }

                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
        <script type="text/javascript" src="/static/js/moment.min.js"></script>
        <script type="text/javascript" src="/static/js/datepicker.all.js"></script>
        <script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
        <script>
            $(document).ready(function(){
                chooseTime()
            })
        </script>
</body>

</html>