<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>
<body>
<?php $this->view->partial("nav");?>
  <div class="walletadmin-content" id="add-wallet-type">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                <div class="page-title"><a href="/<?php echo $pro_no; ?>/wallettype/list">钱包类型管理  </a><span>>> 添加ETH钱包类型</span></div>
                <form action="" method="post" enctype="multipart/form-data">
                    <div class="add-wallet-type">
                      <div>
                        <div>
                          <span>*</span> 合约地址
                        </div>
                        <div>
                          <input type="text" name="token_contract">
                        </div>
                      </div>
                      <div class="wallet-type-abi">
                        <div>
                          <span>*</span> ABI
                        </div>
                        <div>
                          <div><textarea name="coin_abi" id="" cols="30" rows="10"></textarea></div>
    <!--                      <span>提示：该项为必填项</span>-->
                        </div>
                      </div>
                      <div>
                        <div>
                          <span>*</span> 转入最小值
                        </div>
                        <div>
                          <input type="text" name="transfer_min" id='min'>
                        </div>
                      </div>
                    </div>
                    
                    <p class="min-prompt">注释：设置单个地址转入冷钱包的最小值限制，若单个地址内的币种数量不满足设置数量，则不转入冷钱包，避免浪费手续费</p>
                    <div class="wallet-type-btn">
                      <button class="btn btn-primary">提交</button>
                    </div>
                </form>
              </div>
          </div>
      </div>
  </div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>
<script>
  $(document).ready(function(){
    $.fn.walletTypeAdd({})
  })
</script>
</body>
</html>