<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>新贝区块链支付解决方案</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>
<body>
<?php $this->view->partial("nav");?>
  <div class="walletadmin-content" id='wallet-type-detail'>
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                <div class="page-title"><a href="/<?php echo $pro_no; ?>/wallettype/list">钱包类型管理  </a><span>>> 详情</span></div>
                  <div class="table">
                   <table>
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>币名称</th>
                          <th>公链类型</th>
                          <th>操作员</th>
                          <th>创建时间</th>
                          <th>状态</th>
                          <th>操作</th>
                        </tr>
                      </thead>
                      <tbody>
                      <td><?php echo $info['id'];?></td>
                      <td><?php echo $info['coin_symbol'];?></td>
                      <td><?php echo $info['chain_symbol'];?></td>
                      <td><?php echo $info['admin_name'];?></td>
                      <td><?php echo date('Y-m-d,H:i:s',$info['created_at'])?></td>
                      <td>
                                <span>
                                <?php
                                if($info['status']==1) {
                                    echo  "正常";
                                }elseif($info['status'] == 0){
                                    echo "已禁用";
                                }
                                ?>
                                    <span>
                      </td>
                      <td>
                          <?php if($info['status']==1){ ?>
                              <button class="action-btn disabled"><a href="/<?php echo $pro_no; ?>/wallettype/updateStatus?id=<?php echo $info['id']; ?>&status=0" onclick="javascript:return confirm('是否禁用？');">禁用</a></button>
                          <?php }elseif($info['status']==0){ ?>
                              <button class="action-btn open"><a href="/<?php echo $pro_no; ?>/wallettype/updateStatus?id=<?php echo $info['id']; ?>&status=1" onclick="javascript:return confirm('是否启用？');">启用</a></button>
                          <?php } ?>
                      </td>
                      </tbody>
                    </table>

                  <div class="type-detail-desc">
                    <div>
                      <div>转入最小值：</div>
                      <div>
                        <span class="detail-desc-min"><?php echo $info['transfer_min']; ?> <i class="icon icon-edit"></i></span>
                        <form action="" method="post" enctype="multipart/form-data">
                          <span class="detail-desc-min-edit">
                              <input type='text' name="transfer_min">
                              <input type='hidden' name="id" value="<?php echo $info['id']; ?>">
                              <button><i class="icon icon-ok"></i>保存</button>
                          </span>
                        </form>
                      </div>
                    </div>
                    <div>
                      <div>合约地址：</div>
                      <div><?php echo $info['token_contract']; ?></div>
                    </div>
                    <div>
                      <div>ABI：</div>
                      <div><?php echo $info['coin_abi']; ?></div>
                    </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
      <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
      <script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
      <script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>
      <script>
        $(document).ready(function(){
          $.fn.walletTypeDetail({})
        })
      </script>
</body>
</html>