<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/datepicker.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">
</head>
<body>
<?php $this->view->partial("nav");?>
  <div class="walletadmin-content">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                  <form action="" method="get">
                      <select name="chain_id" id="" class="admin-select">
                          <option name="chain_id" value="" <?php if($data['chain_id'] == ""){echo "selected";} ?>>全部</option>
                          <?php foreach($data['chain'] as $item){ ?>
                              <option name="chain_id" value="<?php echo $item['id']; ?>"  <?php if($data['chain_id'] == $item['id']){echo "selected";} ?>><?php echo $item['chain_symbol'];?></option>
                          <?php } ?>
                      </select>

                      <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                          <input type="text" autocomplete="off" name="begin_date" placeholder="开始时间" class="c-datepicker-data-input only-date" <?php if(isset($data['begin_date'])){ if($data['begin_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['begin_date'])."'"; }} ?>>
                      </div>
                      <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                          <input type="text" autocomplete="off" name="end_date" placeholder="结束时间" class="c-datepicker-data-input only-date" <?php if(isset($data['end_date'])){ if($data['end_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['end_date'])."'"; }} ?>>
                      </div>
                      <select name="admin_no" id="" class="admin-select">
                          <option name="admin_no" value="" <?php if($data['admin_no'] == ""){echo "selected";} ?>>全部</option>
                          <?php foreach($data['admin'] as $item){ ?>
                              <option name="admin_no" value ="<?php echo $item['admin_no'] ?>" <?php if($data['admin_no'] == $item['admin_no']){echo "selected";} ?>><?php echo $item['admin_name'] ?></option>
                          <?php } ?>
                      </select>

                      <button class="btn btn-primary search-btn">搜索</button>
                  </form>
              </div>


              <div class="container">
                <div class="page-title">
                    钱包类型管理
                </div>
                  <?php if(strpos($data['permission'],',wallet_type_do,') != false || $data['is_super'] == 1 || $data['is_power'] == 1){ ?>
                    <div class="add-w-t-btn">
                        <a href="/<?php echo $pro_no; ?>/wallettype/add"><button class="action-btn add">添加</button></a>
                    </div>
                  <?php } ?>
                  <div class="table">
                  <table>
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>币名称</th>
                        <th>公链类型</th>
                        <th>操作员</th>
                        <th>创建时间</th>
                        <th>状态</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                    <?php foreach($list as $v){ ?>
                        <tr>
                            <td><?php echo $v['id'];?></td>
                            <td><?php echo $v['coin_symbol'];?></td>
                            <td><?php echo $v['chain_symbol'];?></td>
                            <td><?php echo $v['admin_name'];?></td>
                            <td><?php echo date('Y-m-d,H:i:s',$v['created_at'])?></td>
                            <td>
                                <span>
                                <?php
                                    if($v['status']==1) {
                                        echo  "正常";
                                    }elseif($v['status'] == 0){
                                        echo "已禁用";
                                    }
                                ?>
                                <span>
                            </td>
                            <td>
                                <?php if(strpos($data['permission'],',wallet_type_do,') != false || $data['is_super'] == 1 || $data['is_power'] == 1){ ?>
                                    <?php if($v['status']==1){ ?>
                                        <a href="/<?php echo $pro_no; ?>/wallettype/updateStatus?id=<?php echo $v['id']; ?>&status=0" onclick="javascript:return confirm('是否禁用？');"><button class="action-btn disabled">禁用</button></a>
                                    <?php }elseif($v['status']==0){ ?>
                                        <a href="/<?php echo $pro_no; ?>/wallettype/updateStatus?id=<?php echo $v['id']; ?>&status=1" onclick="javascript:return confirm('是否启用？');"><button class="action-btn open">启用</button></a>
                                    <?php } ?>
                                    
                                    <a href='/<?php echo $pro_no; ?>/wallettype/info?id=<?php echo $v['id'];?>'><button class="action-btn" >详情</button></a>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                  </table>
                  <div class="pagination-box">
                      <?php
                      if($list){
                          //存储页码字符串
                          $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                          //当前页码数，默认当前页码为1
                          $curPage = isset($_GET['page'])?$_GET['page']:1;
                          if($curPage <=5){
                              $begin =1;
                              $end = $data['totalpage']>=10?10:$data['totalpage'];
                          }else{
                              $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                              $begin =$end -9<=1?1:$end -9;
                          }
                          //实现上一页
                          $prev = $data['page'] -1<=1?1:$data['page'] -1;
                          $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                          $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                          //根据起始页与终止页将当前页面的页码显示出来
                          for($i=$begin;$i<=$end;$i++){
                              //使用if实现高亮显示当前点击的页码
                              if($data['page'] == $i){
                                  $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                              }else{
                                  $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                              }
                          }


                          //实现下一页
                          $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                          $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                          $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                          $pageNumString .='</div>';
                          echo $pageNumString;
                      }

                      ?>
                  </div>
                </div>
              </div>
          </div>
      </div>
  </div>

<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/moment.min.js"></script>
<script type="text/javascript" src="/static/js/datepicker.all.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script>
    $(document).ready(function(){
        chooseTime()
    })
</script>
</body>
</html>