<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>新贝区块链支付解决方案</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>
<body>
<?php $this->view->partial("nav");?>

<div class="walletadmin-content">
    <div class="walletadmin-box">
        <div style="min-height: 100vh;background-color: #ECECEC;">
            <h2>LV测试页</h2>
            <span><?php print_r($data); ?></span>
        </div>
    </div>
</div>
</body>
</html>