<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>

    <link href="/static/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/static/css/style.css?v=4.1.0" rel="stylesheet">

    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">

</head>
<body>
<?php $this->view->partial("nav");?>

<div class="walletadmin-content">
    <div class="walletadmin-box">
        <div class="box">

            <div class="container">
                <div class="page-title">道具发送请求记录</div>
                <br>

                <a href="/manager/prop/dealView?search=1"><button class='btn btn-primary'> &nbsp 成功 &nbsp </button></a>
                <a href="/manager/prop/dealView?search=0"><button class='btn btn-primary'> &nbsp&nbsp&nbsp 请求中 &nbsp&nbsp&nbsp </button></a>
                <a href="/manager/prop/dealView?search=2"><button class='btn btn-primary'> &nbsp&nbsp&nbsp 已拒绝 &nbsp&nbsp&nbsp </button></a>
                <a href="/manager/prop/dealView?search=-1"><button class='btn btn-primary'> &nbsp&nbsp&nbsp 发送失败 &nbsp&nbsp&nbsp </button></a>
                <a href="/manager/prop/dealView"><button class='btn btn-primary'> &nbsp&nbsp&nbsp 全部 &nbsp&nbsp&nbsp </button></a>

                <div class="table">
                    <table>
                        <thead>
                        <tr>
                            <th style="text-align: center">id</th>
                            <th style="text-align: center">昵称</th>
                            <th style="text-align: center">道具</th>
                            <th style="text-align: center">服务器</th>
                            <th style="text-align: center">备注</th>
                            <th style="text-align: center">是否发送</th>
                            <th style="text-align: center">请求人</th>
                            <th style="text-align: center">处理人</th>
                            <th style="text-align: center">处理时间</th>
                            <th style="text-align: center">处理</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php foreach($list as $v){ ?>
                            <tr>
                                <td><?php echo $v['id'];?></td>
                                <td>
                                        <span>
                                            <?php
                                            if($v['nickname'] == '') {
                                                echo  "全部";
                                            }else{
                                                echo $v['nickname'];
                                            }
                                            ?>
                                            <span>
                                </td>
                                <td><?php echo $v['item'];?></td>
                                <td><?php echo $v['server_name'];?></td>
                                <td><?php echo $v['remark'];?></td>
                                <td>
                                        <span>
                                            <?php
                                            if($v['is_send'] == 0) {
                                                echo  '请求中';
                                            }elseif($v['is_send'] == 1){
                                                echo '已发送';
                                            }elseif($v['is_send'] == 2){
                                                echo '已拒绝';
                                            }elseif($v['is_send'] == -1){
                                                echo '发送失败';
                                            }
                                            ?>
                                            <span>
                                </td>
                                <td><?php echo $v['req_admin_name'];?></td>
                                <td><?php echo $v['deal_admin_name'];?></td>
                                <td>
                                    <?php if($v['created_at'] != $v['updated_at']){
                                        echo date('Y-m-d H:i:s',$v['updated_at']);
                                    } ?>
                                </td>
                                <td>
                                    <?php if($v['is_send'] != 1 && $v['is_send'] != 2){ ?>
                                        <a href="/manager/prop/deal?id=<?php echo $v['id']; ?>&is_send=2" onclick="javascript:return confirm('是否确认拒绝？');"><button class="action-btn disabled">拒绝</button></a>
                                        <a href="/manager/prop/deal?id=<?php echo $v['id']; ?>&is_send=1" onclick="javascript:return confirm('是否确认发送？');"><button class="action-btn ">通过</button></a>
                                    <?php } ?>
                                </td>

                            </tr>
                        <?php } ?>


                        </tbody>
                    </table>
                    <div class="pagination-box">

                        <?php
                        if(isset($list) && $list != ''){
                            //存储页码字符串
                            $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                            //当前页码数，默认当前页码为1
                            $curPage = isset($_GET['page'])?$_GET['page']:1;
                            if($curPage <=5){
                                $begin =1;
                                $end = $data['totalpage']>=10?10:$data['totalpage'];
                            }else{
                                $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                                $begin =$end -9<=1?1:$end -9;
                            }
                            //实现上一页
                            $prev = $data['page'] -1<=1?1:$data['page'] -1;
                            $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                            $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                            //根据起始页与终止页将当前页面的页码显示出来
                            for($i=$begin;$i<=$end;$i++){
                                //使用if实现高亮显示当前点击的页码
                                if($data['page'] == $i){
                                    $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                }else{
                                    $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                }
                            }


                            //实现下一页
                            $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                            $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                            $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                            $pageNumString .='</div>';
                            echo $pageNumString;

                        }

                        ?>

                    </div>

                </div>
            </div>

            <div id="serverUrl" style="color: #E1E1EB"><?php echo $server_url; ?></div>
        </div>
    </div>
    <script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
    <script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>

    <script src="/static/js/jquery.min.js?v=2.1.4"></script>
    <script src="/static/js/content.js?v=1.0.0"></script>
    <script src="/static/js/config.js"></script>
    <script src="/static/js/common.js"></script>

    <script type="text/javascript">
        jQuery.support.cors = true;
        $(function(){
            var zoneValList = [];
            var server_url = $('#serverUrl').text()

//              url = "http://" + RemoteAddr + ":" + Port + "/gm/getitemlist";
            url = server_url + "/gm/getitemlist";
            var item;
            $.ajax({
                url: url,
                type: "GET",
                dataType:"json",
                async: false,
                success: function(data){
                    //On ajax success do this
                    console.info("success.");
                    console.log(data["success"]);
                    if (data["success"] == true){
                        delete(data["success"])
                        // console.log(data);
                        // alert("Settings is Ok. The Machine is rebooting.");
                        $.each(data, function(idx,val){
                            item += "<option value="+idx+">"+idx+" "+val;
                            // console.log(idx, val)
                            item += "</option>";
                        });
                        $(".itemList").html(item);
                        $(".itemList").chosen();
                    }else{
                        return;
                    }
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    //On error do this
                    console.info("error.");
                    // if (xhr.status == 200) {
                    //     alert(ajaxOptions);
                    // } else {
                    //     alert(xhr.status);
                    //     alert(thrownError);
                    // }
                    // window.location.href = "500.html";
                }
            });

            // $(".itemList").chosen();

            // 添加道具
            $(".itemAdd").click(function(){
                if(!$(".itemNum").val()){
                    layer.tips('亲，请输入道具数量哦~', ".itemNum");
                    return;
                }
                var value = $(".itemList").val() + "," + $(".itemNum").val();
                var itemName = $(".itemList").find("option:selected").text();
                itemName = itemName.substr( itemName.indexOf("-") + 1, itemName.length).replace( ' ', '');
                $(".itemSelected").append("<option value='" + value + "' selected>" + itemName + " — " + $(".itemNum").val() + "个" + " </option>");
//                  $(".itemSelected").append("<option value='" + value + "'>" + itemName + " — " + $(".itemNum").val() + "个" + " </option>");
            });

            // 追加道具
            $(".itemAppend").click(function(){
                if($(".lastItem option").size() <= 0){
                    return;
                }
                $(".lastItem option").each(function(){
                    $(".itemSelected").append("<option value='" + $(this).val() + "'>" + $(this).text() + "</option>");
                    $(this).remove();
                });
            });

            // 删除已选道具
            $(".itemSelected").dblclick(function(){
                $(".itemSelected option[value='" + $(this).val() + "']").remove();
            });

            // submit
            $(".send").click(function(){

                if(!$("input[name='mailtitle']").val() || !$("input[name='mailcontent']").val() || !$("select[name='itemSelected[]']").text()){
                    //tips层
                    layer.tips('亲，有必填参数未填写哦~', ".send");
                    return;
                }

//                  url = "http://" + RemoteAddr + ":" + Port +  "/manager/senditem";
                url = server_url +  "/manager/senditem";

//                  $.ajax({
//                      url: url,
//                      type: "POST",
//                      data: getParams(),
//                      // contentType: "application/json",
//                      dataType:"json",
//                      success: function(data){
//                          //On ajax success do this
//                          console.info("success.");
//                          if (data["success"]){
//                              alert("发送成功");
//                          }else{
//                              alert("发送失败");
//                              console.log("fail");
//                              return;
//                          }
//
//                      },
//                      error: function(xhr, ajaxOptions, thrownError) {
//                          //On error do this
//                          console.info("error.");
//                          console.log(xhr);
//                          if (xhr.status == 200) {
//                              alert(ajaxOptions);
//                          } else {
//                              alert(xhr.status);
//                              alert(thrownError);
//                          }
//                      }
//                  });
            });

            $(".zone").change(function(){
                showZone();
            });

            function showZone(){
                zoneValList = [];
                var zoneNameList = [];
                $(".zone option:selected").each(function(){
                    zoneNameList.push($(this).text());
                    zoneValList.push($(this).val());
                });
                $(".zoneList").text(zoneNameList.join(","));
            }

            $(".channel").change(function(){
                showChan();
            });





            // 获取参数
            function getParams(){
                var itemStr = "";
                $(".itemSelected option").each(function(){
                    itemStr += $(this).val() + ";";
                });
                return {
                    zones: zoneValList.join("|"),
                    nickname: $("input[name='nickname']").val(),
                    mailtitle: $("input[name='mailtitle']").val(),
                    mailcontent: $("input[name='mailcontent']").val(),
                    itemstr : itemStr.substring(0, itemStr.length - 1)
                }
            }
        })
    </script>

    <!--<script>-->
    <!--  $(document).ready(function(){-->
    <!--    $.fn.adminAdd({})-->
    <!--  });-->
    <!---->
    <!--  $("#eye").click(function() {-->
    <!--      if($(".password").attr("type") == "text") {-->
    <!--          $(".password").attr("type", "password");-->
    <!--          $("#eye span").removeClass("icon-yanjing_kai");-->
    <!--          $("#eye span").addClass("icon-yanjing_bi");-->
    <!--      } else {-->
    <!--          $(".password").attr("type", "text");-->
    <!--          $("#eye span").removeClass("icon-yanjing_bi");-->
    <!--          $("#eye span").addClass("icon-yanjing_kai");-->
    <!---->
    <!--      }-->
    <!--  });-->
    <!--</script>-->
</body>
</html>