<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>新贝区块链支付解决方案</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/datepicker.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">
</head>
<body>
<?php $this->view->partial("nav");?>
  <div class="walletadmin-content">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                <div style="font-size: 16px;">
                    <span style="float: left;margin-right: 220px;">EOS账户:<?php echo $address; ?></span>

                    <span>余额:<?php echo $account; ?></span>
                </div>
              </div>


              <div class="container">
                    <div class="page-title">
                        资源管理
                    </div>

                   <div class="log-detail-desc">
                       <div  style="padding: 20px;">
                               <div style="border-bottom: 1px solid  #F0F0F0;width:90%;margin:15px;padding-bottom:10px">
                                   <div style="float: left;margin-right: 150px;width: 200px;">
                                       <div>
                                            <span style="font-size: 16px;">内存
                                                <span style="color: red;"><?php if($resourceData['ram_available'] <= $minData['RAM']){ echo "(不足)"; } ?></span>
                                            </span>
                                       </div>
                                       <div>
                                           <span>可用&nbsp;&nbsp;<?php echo $resourceData['ram_available']; ?></span><br>
                                           <span>总量&nbsp;&nbsp;<?php echo $resourceData['ram_quota']; ?></span>
                                       </div>
                                   </div>
                                   <div style="float: left;">
                                       <div>
                                            <span style="font-size: 16px;">
                                                当前内存价格 ≈ <?php echo $resource_price['RAM']; ?> EOS/KB
                                            </span>
                                       </div>
                                       <div class="eos_resource_buy">
                                           <form action="" onsubmit="return false">
                                               <input type="text" class="ram_num" name="coin_amount"  placeholder="请输入EOS数量">
                                               <button class="buy_ram">买入</button>
                                           </form>
                                       </div>
                                   </div>
                                   <div style="clear: both;"></div>
                               </div>
                               <div style="margin:15px;">
                                   <div style="float: left;margin-right: 150px;width: 200px;">
                                       <li>
                                        <span style="font-size: 16px;">CPU
                                             <span style="color: red;"><?php if($resourceData['cpu_available'] <= $minData['CPU']){ echo "(不足)"; } ?></span>
                                        </span>
                                       </li>
                                       <li style="width:90%;margin:5px;">
                                           <span>可用&nbsp;&nbsp;<?php echo $resourceData['cpu_available']; ?></span><br>
                                           <span>总量&nbsp;&nbsp;<?php echo $resourceData['cpu_quota']; ?></span>
                                       </li>
                                   </div>
                                   <div style="float: left;">
                                       <div>
                                            <span style="font-size: 16px;">
                                                当前CPU价格 ≈ <?php echo $resource_price['CPU']; ?> EOS/ms
                                            </span>
                                       </div>
                                       <div class="eos_resource_buy">
                                           <form action="" onsubmit="return false">
                                               <input type="text" name="coin_amount" class="cpu_num"  placeholder="请输入EOS数量">
                                           </form>
                                       </div>
                                   </div>
                                   <div style="clear: both;"></div>
                               </div>
                               <div style="margin:15px;">
                                   <div style="float: left;margin-right: 150px;width: 200px;">
                                       <li>
                                        <span style="font-size: 16px;">NET
                                             <span style="color: red;"><?php if($resourceData['net_available'] <= $minData['NET']){ echo "(不足)"; } ?></span>
                                        </span>
                                       </li>
                                       <li style="width:90%;margin:5px;">
                                           <span>可用&nbsp;&nbsp;<?php echo $resourceData['net_available']; ?></span><br>
                                           <span>总量&nbsp;&nbsp;<?php echo $resourceData['net_quota']; ?></span>
                                       </li>
                                   </div>
                                   <div style="float: left;">
                                       <div>
                                            <span style="font-size: 16px;">
                                                当前NET价格 ≈ <?php echo $resource_price['NET']; ?> EOS/KB
                                            </span>
                                       </div>
                                       <div class="eos_resource_buy">
                                           <form action="" onsubmit="return false">
                                               <input type="text" name="coin_amount" class="net_num"  placeholder="请输入EOS数量">
                                               <button class="buy_cpu_and_net">买入</button>
                                           </form>
                                       </div>
                                   </div>
                                   <div style="clear: both;"></div>
                               </div>

                       </div>
                   </div>

              </div>
          </div>
      </div>
  </div>

<div class="dialog" id="buyRam">
    <div class="wrapper">
        <form action="/<?php echo $pro_no; ?>/buyRam" method="post" enctype="multipart/form-data">
            <div class="dialog-title">
                请输入出账钱包密码
            </div>
            <div class="out-wallet-pwd-dialog-input">
                <input type="password" class="input-primary" name="password" placeholder="请输入密码">
                <input type="hidden" name="ram_num" id="ram_num" value="">
                <input type="hidden" name="chain_symbol" value="EOS">
            </div>
            <div class="out-wallet-pwd-dialog-btn">
                <button class="w-btn">提交</button>
            </div>
        </form>
    </div>
</div>

<div class="dialog" id="buyCpuNet">
    <div class="wrapper">
        <form action="/<?php echo $pro_no; ?>/buyCpuNet" method="post" enctype="multipart/form-data">
            <div class="dialog-title">
                请输入出账钱包密码
            </div>
            <div class="out-wallet-pwd-dialog-input">
                <input type="password" class="input-primary" name="password" placeholder="请输入密码">
                <input type="hidden" name="cpu_num" id="cpu_num" value="">
                <input type="hidden" name="net_num" id="net_num" value="">
                <input type="hidden" name="chain_symbol" value="EOS">
            </div>
            <div class="out-wallet-pwd-dialog-btn">
                <button class="w-btn">提交</button>
            </div>
        </form>
    </div>

</div>

<div class="message">
    <div class="message_title"></div>
</div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>
<script type="text/javascript" src="/static/js/moment.min.js"></script>
<script type="text/javascript" src="/static/js/datepicker.all.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script>
    $(document).ready(function(){
        $('.ram_num').val("");
        $('.cpu_num').val("");
        $('.net_num').val("");
        $.fn.resourceManage()
    })
</script>
</body>
</html>