<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>
<body>
  <?php $this->view->partial("nav"); ?>
  <div class="walletadmin-content" id='project-detail'>
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                  <div class="project-detail">
                      <div class="page-title">项目详情</div>
                  </div>
                  <div class="detail-desc">
                    <ul>
                      <li>
                        <span>项目名称</span>
                        <span><?php echo $pro_name ?></span>
                      </li>
                      <li>
                        <span>项目负责人</span>
                        <span><?php echo $contacts_name ?></span>
                      </li>
                      <li>
                        <span>公司名称</span>
                        <span><?php echo $pro_name ?></span>
                      </li>
                      <li>
                        <span>绑定手机号</span>
                        <span><?php echo $contacts_phone ?></span>
                      </li>
                        <li>
                            <span>登录链接</span>
                            <span><a style="color: lightseagreen;" href="<?php echo $login_url ?>" target="_blank"><?php echo $login_url ?></a></span>
                        </li>
                    </ul>
                    <ul>
                      <li>
                        <span>钱包接口地址</span>
                        <span><?php echo $project_wallet_url ?></span>
                      </li>
                      <li>
                        <span>充提现状态接口地址</span>
                        <span><?php echo $project_hash_url ?></span>
                      </li>
                      <li>
                        <span>接口密钥</span>
                        <span><?php echo $secret_key ?> </span>
                        <i class="icon icon-copy" id='copy-text-btn'></i><input style="opacity: 0;" type="text" id="copy-text" value='<?php echo $secret_key ?>'>
                      </li>
                    <li>
                        <span>数据传输接口密钥</span>
                        <span><?php echo $encryption_security_url ?> </span>
                        <i class="icon icon-copy" id='copy-text-btn2'></i><input style="opacity: 0;" type="text" id="copy-text2" value='<?php echo $encryption_security_url ?>'>
                    </li>
                      <li>
                        <span>固定IP/域名</span>
                        <span><?php echo $security_url ?></span>
                      </li>
                    </ul>

                    <div class="cl"></div>
                  </div>
              </div>
              <div class="container">
                  <div class="project-detail">
                      <div class="page-title">冷钱包地址</div>
                  </div>
                  <div class="cold-wallet-address wallet-address">
                      <?php foreach ($lengWallet as $lengWallets){ ?>
                            <div class='copy copy-save'>
                                  <span class='lian-name'><?php echo $lengWallets['chain_symbol']; ?>：</span>
                                <?php if($lengWallets['chain_symbol'] == 'EOS'){ ?>
                                    <input  style="min-width:400px;" type='text' id="coldAddressData_<?php echo $lengWallets['id']; ?>" name='address' value='<?php echo $lengWallets['address']; ?>'>
                                    标签:<input  style="min-width:350px;" id="coldAddressMemo_<?php echo $lengWallets['id']; ?>" type='text' name='memo' value='<?php echo $lengWallets['memo']; ?>'>
                                <?php }else{ ?>
                                    <input  type='text' id="coldAddressData_<?php echo $lengWallets['id']; ?>" name='address' value='<?php echo $lengWallets['address']; ?>'>
                                    <input type="hidden" id="coldAddressMemo_<?php echo $lengWallets['id']; ?>" name="memo" value="">
                                <?php } ?>
                                <button  onclick="setValue(<?php echo $lengWallets['id'] ?>)"><i class='icon icon-ok'></i>保存</button>

                            </div>
                            <div class='copy copy-edit active'>
                                  <span class='lian-name'><?php echo $lengWallets['chain_symbol'] ?>：</span>
                                  <span><?php echo $lengWallets['address'] ?></span>&nbsp;&nbsp;
                                <?php if($lengWallets['chain_symbol'] == 'EOS'){ ?>
                                    <span>标签:&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $lengWallets['memo'] ?></span>
                                <?php } ?>
                                <?php if(strpos($permission['permission'],',project_detail_do,') != false || $permission['is_super'] == 1 || $data['is_power'] == 1){ ?>
                                    <!--操作权限-->
                                    <i class='icon icon-edit'></i>
                                <?php } ?>
                          </div>
                       <?php } ?>


                      <!--操作权限-->
                      <?php
                      if(strpos($permission['permission'],',project_detail_do,') != false || $permission['is_super'] == 1 || $data['is_power'] == 1){
                          if($chains != []){ ?>
                          <div>
                            <form action='/<?php echo $pro_no; ?>/projectWallet/add' enctype='multipart/form-data' method='post'>
                                <select name='chain_id' id="select_chain_symbol"  class='admin-select' onchange="eos_address()">";
                                    <?php foreach ($chains as $chain) { ?>
                                        <option   name='chain_id' value='<?php echo $chain['id'].','.$chain['chain_symbol'];?>' ><?php echo $chain['chain_symbol'];?></option>
                                    <?php } ?>
                                </select>

                                <span id="add_content">
                                    <input type='text' placeholder='请输入/粘贴冷钱包地址' name='address'>
                                    <input type='hidden' name='type'  value='1'>
                                    <input type='hidden' name='memo'  value=''>
                                    <button><i class='icon icon-ok'></i>保存</button>
                                </span>

<!--                                <input style="min-width:400px;" type='text' placeholder='请输入/粘贴冷钱包地址' name='address'>标签:<input style="min-width:400px;" type='text' placeholder='可选填' name='memo'>-->
<!--                                <input type='hidden' name='type'  value='1'>-->
<!--                                <button><i class='icon icon-ok'></i>保存</button>-->
<!---->
<!--                                <input type='text' placeholder='请输入/粘贴冷钱包地址' name='address'>-->
<!--                                <input type='hidden' name='type'  value='1'>-->
<!--                                <input type='hidden' name='memo'  value=''>-->
<!--                                <button><i class='icon icon-ok'></i>保存</button>-->
                            </form>
                          </div>
                      <?php }} ?>
                      <div><i class="icon icon-mark"></i><span style="color: red;">   请填写支持USDT的BTC地址,如:1开头的BTC地址 </span></div>

                  </div>
              </div>
              <div class="container">
                  <div class="project-detail">
                      <div class="page-title">出账钱包地址</div>
                  </div>
                  <div class="out-wallet-address wallet-address">
                      <?php foreach ($transferWallet as $transferWallets){ ?>
                         <div class='copy copy-edit active'>
                              <span class='lian-name'><?php echo $transferWallets['chain_symbol'];?>:</span>

                             <?php if($transferWallets['chain_symbol'] == 'EOS'){ ?>
                                 <span><?php echo $transferWallets['address'];?></span>&nbsp;&nbsp;
                             <?php }else{ ?>
                                <span><?php echo $transferWallets['address'];?></span>
                             <?php } ?>
                          </div>
                      <?php } ?>

                      <?php if(strpos($permission['permission'],',project_detail_do,') != false || $permission['is_super'] == 1 || $data['is_power'] == 1){ ?>
<!--                        操作权限-->
                      <?php if($transferChains != []){ ?>
                          <div>
                            <select name='chain_id' class='admin-select' id="transferChains" onchange="noticeFunction()">";

                            <?php foreach ($transferChains as $chain) { ?>
                                  <option name='chain_id' value='<?php echo $chain['id'].','.$chain['chain_symbol'];?>'><?php echo $chain['chain_symbol'];?></option>
                            <?php  } ?>

                            </select>
                                <input id="transferChainsNotice" type='password'  placeholder='请设置包含小写英文与数字组成的8~20位的字符密码' name='password' value="">
                                <input type='hidden' name='type'  value='2'>
                                <button class="out-verb-btn"><i class='icon icon-ok'></i>生成</button>
                          </div>
                      <?php }} ?>
                      <div id="notice"><i class="icon icon-mark"></i><span style="color: red;">   密码用于保护私钥和交易授权，强度非常重要。本系统不储存密码，也无法帮您找回，请务必牢记。</span><br><br></div>

                  </div>
              </div>
              <div class="container">
                  <div class="project-detail">
                      <div class="page-title">手续费钱包地址</div>
                  </div>
                  <div class="out-wallet-address wallet-address">
                      <?php foreach ($feeWallet as $feeWallets){ ?>
                          <div class='copy copy-edit active'>
                              <span class='lian-name'><?php echo $feeWallets['chain_symbol'];?>:</span>
                              <span><?php echo $feeWallets['address'];?></span>
                          </div>
                      <?php } ?>
                      <?php if(strpos($permission['permission'],',project_detail_do,') != false || $permission['is_super'] == 1 || $data['is_power'] == 1){ ?>
<!--                        操作权限-->
                      <?php if($feeChains != []){ ?>
                          <div>
                              <select name='chain_id' class='admin-select'>";
                                  <?php foreach ($feeChains as $chain) { ?>
                                      <?php if($chain['chain_symbol'] == 'EOS'){continue;} ?>
                                      <option name='chain_id' value='<?php echo $chain['id'].','.$chain['chain_symbol'];?>' selected><?php echo $chain['chain_symbol'];?></option>
                                  <?php  } ?>
                              </select>

                              <input type='password' placeholder='请设置包含小写英文与数字组成的8~20位的字符密码' name='password'>
                              <input type='hidden' name='type'  value='3'>
                              <button class="out-verb-btn"><i class='icon icon-ok'></i>生成</button>
                          </div>
                      <?php }} ?>
                      <div><i class="icon icon-mark"></i><span style="color: red;">   密码用于保护私钥和交易授权，强度非常重要。本系统不储存密码，也无法帮您找回，请务必牢记。</span></div>

                  </div>
              </div>
          </div>
      </div>
  </div>

<div class="dialog" id='pwd-confirm'>
  <div class="wrapper">
      <form action='' onsubmit="return false" enctype='multipart/form-data' method='post'>
      <div class="dialog-title" id="pwd-confirm-title">
          密码确认
      </div>
      <div class="pwd-warn" id="pwd-confirm-notice">
          密码请妥善保管，一旦丢失无法找回
      </div>
      <div class="pwd-confirm-btn">
          <input type="hidden" class="chain_id" name="chain_id" value="">
          <input type="hidden" class="password" name="password">
          <input type="hidden" class="address" name="address">
          <input type="hidden" class="type" name="type" value="">
          <input type="hidden" name="memo" value="">
          <input type="hidden" id="pro_no" value="<?php echo $pro_no; ?>">
          <span class="w-btn cancel">取消</span>
          <button class="w-btn confirm" onclick="projectWalletAdd()">确认</button>
      </div>
      </form>
  </div>
</div>


<div class="dialog" id='walletd-login-pwd'>
  <div class="wrapper">
      <form action='/<?php echo $pro_no; ?>/projectWallet/edit' enctype='multipart/form-data' method='post'>
        <div class="dialog-title">
            请输入账号密码
        </div>
        <div class="pwd-input">
            <input type="password" class="input-primary" placeholder="密码" name="password">
        </div>
        <div class="login-pwd-confirm">
            <input type="hidden" class="coldId" name="coldId" value="">
            <input type="hidden" id="coldData" class="coldData" name="coldData" value="">
            <input type="hidden" id="coldMemo" class="coldMemo" name="coldMemo" value="">
            <button class="w-btn">提交</button>
        </div>
      </form>
  </div>
</div>
  
<div class="dialog dialog-not-click" id='password-copy-confirm'>
  <div class="wrapper">
      <div class="generate-suc-padding">
          <p style="color: red;margin-bottom: 30px;">请谨记并保存该密码,密码一旦丢失无法找回</p >
          <p><span id="password-copy-text" style="text-align: center;word-break: break-all;"></span></p>
          <p style="margin-left: 135px;margin-top: 10px">
              <span style="color: #26A38F;" id='copy-password-btn'><i class="icon icon-copy"></i> 复制</span>
              <input style="opacity: 0;" type="text" id="copy-password" value=''></p>
<!--          <a href="/--><?php //echo $pro_no; ?><!--/projectWallet/passwordConfirm"></a>-->
          <button class="w-btn" id="password-confirm-button">验证密码</button>
          <p style="color: red;">该密码已发送给超级管理员,请注意查收</p>
      </div>
  </div>
</div>

<div class="dialog dialog-not-click" id='password-confirm-form' >
  <div class="wrapper">
      <form action='' onsubmit="return false" enctype='multipart/form-data' method='post'>
          <div class="dialog-title" style="color: red;">
              请输入或粘贴密码,确认生成账户
          </div>
          <div class="pwd-input">
              <input type="password" class="input-primary copyPassword" placeholder="密码" name="password">
              <input type="hidden" class="pro_no" value="<?php echo $pro_no; ?>">
              <input type="hidden" class="address" name="address" value="">
          </div>
          <div class="login-pwd-confirm">
              <button class="w-btn" onclick="passwordConfirm()">确认密码</button>
              <p style="color: red;margin-top: 10px;">该密码已发送给超级管理员,请注意查收</p>
          </div>
      </form>
  </div>
</div>
  
<div class="message">
  <div class="message_title"></div>
</div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>
<script>
  $(document).ready(function(){

      $.fn.projectDetail();

      window.eos_address = function () {
          var select = $("#select_chain_symbol").find("option:selected").html();
          if(select === 'EOS'){
              $("#add_content").html("<input style=\"min-width:300px;\" type='text' placeholder='请输入/粘贴冷钱包地址' name='address' />标签:<input style=\"min-width:300px;\" type='text' placeholder='可选填' name='memo' />\n" +
                  "                                <input type='hidden' name='type'  value='1' />\n" +
                  "                                <button><i class='icon icon-ok'></i>保存</button>");
          }else{
              $("#add_content").html("<input type='text' placeholder='请输入/粘贴冷钱包地址' name='address' />\n" +
                  "              <input type='hidden' name='type'  value='1' />\n" +
                  "              <input type='hidden' name='memo'  value='' />\n" +
                  "              <button><i class='icon icon-ok'></i>保存</button>");
          }
      };

      window.noticeFunction = function () {
          var select = $("#transferChains").find("option:selected").html();
          if(select === 'EOS'){
              $('#transferChainsNotice').attr("placeholder","EOS账户必须由小写字符和数字组成的12个字符,数字只能选用从1至5的五位数字");
              $('#transferChainsNotice').attr("name","address");
              $('#transferChainsNotice').attr("type","text");
          }else{
              $('#transferChainsNotice').attr("placeholder","请设置包含小写英文与数字组成的8~20位的字符密码");
              $('#transferChainsNotice').attr("name","password");
              $('#transferChainsNotice').attr("type","password");
          }
      };

      noticeFunction();

  });
</script>
</body>
</html>