<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title></title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>
<body>
    <?php $this->view->partial("nav");?>
    <div class="walletadmin-content">
      <div class="walletadmin-box walletadmin-list">
          <div class="box">
              <div class="container">
                  <div class="page-title">道具列表</div>
                  <div class="table">
                      <table>
                        <thead>
                            <tr>
                                <th width="50%">Id</th>
                                <th width="50%">道具名</th>
                            </tr>
                        </thead>
                        <tbody>

                        <?php foreach($list as $k => $v){ ?>
                                <tr>
                                    <td><?php echo $k;?></td>
                                    <td><?php echo $v;?></td>

                                </tr>
                        <?php } ?>

                        
                        </tbody>
                      </table>
                          
                  </div>
              </div>
          </div>
      </div>
  </div>

<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
</body>
</html>