<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
</head>
<body>
<?php $this->view->partial("nav");?>
  <div class="walletadmin-content" id="add-wallet-type">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                  <div>
                      <div class="page-title">请输入相关信息查询</div>
                      <form action="" method="post" enctype="multipart/form-data" onsubmit="return false">
                          <div class="add-wallet-type">
                              <div>
                                  <div>
                                      <span>*</span> 合约地址
                                  </div>
                                  <div>
                                      <input type="text" name="token_contract" class="token_contract">
                                  </div>
                              </div>
                              <div class="wallet-type-abi">
                                  <div>
                                      <span>*</span> ABI
                                  </div>
                                  <div>
                                      <div><textarea name="abi" id="" cols="30" rows="10" class="abi"></textarea></div>
                                  </div>
                              </div>
                              <div>
                                  <div>
                                      <span>*</span> 充值地址
                                  </div>
                                  <div>
                                      <input type="text" name="deposit_address" class="deposit_address">
                                  </div>
                              </div>
                              <div>
                                  <div>
                                      <span>*</span> 充值Hash
                                  </div>
                                  <div>
                                      <input type="text" name="hash" class="hash">
                                  </div>
                              </div>
                          </div>
                          <div class="wallet-type-btn" style="margin-top: 15px;">
                              <input type="hidden" name="pro_no" class="pro_no" value="<?php echo $pro_no; ?>">
                              <button class="btn btn-primary" onclick="selectUnknowncoinOrder()">查询</button>
                          </div>
                      </form>
                  </div>

                  <div style="margin: 20px auto;display: none;" id="show-unknowncoin-order">
                      <div class="page-title">查询结果</div>
                      <form action="" method="post" enctype="multipart/form-data" onsubmit="return false">
                          <div style="margin:18px 8px;">
                              <div>
                                  充值地址:<span id="deposit_address"></span>
                              </div>
                              <div>
                                  所属批次:<span id="batch_no"></span>
                              </div>
                              <div>
                                  Hash:<span id="hash"></span>
                              </div>
                              <div>
                                  金额:<span id="amount"></span>&nbsp;&nbsp;<span id="coin_type"></span>
                              </div>
                          </div>
                          <div style="margin-top: 15px;">
                              <button class="btn btn-primary" style="width: 200px;" id="unknowncoin-transfer">转出冷钱包</button>
                          </div>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>

<div class="dialog " id="show-unknowncoin-transfer">
    <div class="wrapper">
        <form action="" onsubmit="return false" method="post" enctype="multipart/form-data">
            <div class="dialog-title">
                请输入该批次的密码
            </div>
            <div class="out-cold-prompt">
                批次号:
                <span id="out-cold-batchNo-text"></span>
            </div>
            <div class="out-cold-pwd">
                <input type="password" class="input-primary password1" placeholder="密码一" name="password1">
                <input type="password" class="input-primary ui-margin password2" placeholder="密码二" name="password2">
                <input type="password" class="input-primary password3" placeholder="密码三" name="password3">
                <div class="cl"></div>
            </div>
            <div class="out-cold-prompt">
                密码提示:
                <span id="out-cold-prompt-text"></span>
            </div>
            <div style="color: red;">
                <p>提示:转出币种将扣除相关手续费,请确保手续费钱包余额充足</p>
                <p style="padding-left: 30px">转出记录显示在项目钱包流水中,币种类型为“其他”,</p>
                <p style="padding-left: 30px">若出现转出失败,请重新操作此流程</p>
                <p style="padding-left: 30px">转出至该币种对应的公链冷钱包中,请确保相关钱包有该币种.</p>
            </div>

            <div class="out-cold-confirm">
<!--                <input type="hidden" name="pro_no" value="--><?php //echo $pro_no; ?><!--">-->
<!--                <input type="hidden" class="batch_no" name="batch_no" value="">-->
<!--                <input type="hidden" class="coin_type" name="coin_type" >-->
<!--                <input type="hidden" class="address" name="address" >-->
<!--                <input type="hidden" class="abi" name="abi" >-->
<!--                <input type="hidden" class="token_contract" name="token_contract" >-->
<!--                <input type="hidden" class="num" name="num" >-->
                <input type="hidden" class="decimals" name="decimals" >

                <button class="w-btn" id="transfer">
                    提交
                </button>
            </div>
        </form>
    </div>
</div>

<div class="dialog dialog-not-click" id='show-unknowncoin-transfer-notice'>
    <div class="wrapper">
        <div class="generate-suc-padding" style="text-align: center;padding:20px;">
            <div style="word-break: break-all;">
                <span id="show-transfer-result"></span>
            </div>
            <button class="w-btn" id="confirm-transfer-notice" onclick="window.location.reload();">确定</button>
        </div>
    </div>
</div>

<div class="message">
    <div class="message_title"></div>
</div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script type="text/javascript" src="/static/js/fenziofficial_admin.js"></script>

</body>
</html>