<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="format-detection" content="telephone=no">
     <meta name="renderer" content="webkit">
    <link href="/newpay_favicon.ico" type="image/x-icon" rel="shortcut icon" /><title>我的战舰养成计划</title>
    <link rel="stylesheet" href="/static/css/inexwalletadmin.css">
    <link rel="stylesheet" href="/static/css/theme-wallet.css">
    <link rel="stylesheet" href="/static/css/datepicker.css">
    <link rel="stylesheet" href="/static/css/iconfont.css">
</head>
<body>
<?php $this->view->partial("nav");?>

  <div class="walletadmin-content" id="wallet-record">
      <div class="walletadmin-box">
          <div class="box">
              <div class="container">
                  <form action="" method="get">
                        <div>
                            <select name="coin_id" id="" class="admin-select">
                                <option value="" name="coin_id" <?php if($data['coin_id'] == ""){echo "selected";} ?>>全部</option>
                                <?php foreach($data['coin'] as $item){ ?>
                                    <option name="coin_id" value="<?php echo $item['id']; ?>"  <?php if($data['coin_id'] == $item['id']){echo "selected";} ?>><?php echo $item['coin_symbol'];?></option>
                                <?php } ?>
                            </select>

                            <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                <input type="text" autocomplete="off" name="begin_date" placeholder="开始时间" class="c-datepicker-data-input only-date" <?php if(isset($data['begin_date'])){ if($data['begin_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['begin_date'])."'"; }} ?>>
                            </div>
                            <div class="c-datepicker-date-editor c-datepicker-single-editor J-datepicker-day">
                                <input type="text" autocomplete="off" name="end_date" placeholder="结束时间" class="c-datepicker-data-input only-date" <?php if(isset($data['end_date'])){ if($data['end_date'] == ''){ echo  "value=''";  }else{ echo "value='".date('Y-m-d H:i:s',$data['end_date'])."'"; }} ?>>
                            </div>

                            <select name="flow_type" id="" class="admin-select">
                                <option value=""  <?php if($data['flow_type'] == '') echo "selected"  ?>>全部</option>
                                <option value="1" <?php if($data['flow_type'] == '1') echo "selected"  ?>>收入</option>
                                <option value="0" <?php if($data['flow_type'] == '0') echo "selected"  ?>>支出</option>
                            </select>
                            <select name="status" id="" class="admin-select">
                                <option value=""  <?php if($data['status'] == '') echo "selected"  ?>>全部</option>
                                <option value="1" <?php if($data['status'] == '1') echo "selected"  ?>>正常</option>
                                <option value="0" <?php if($data['status'] == '0') echo "selected"  ?>>失败</option>
                            </select>
                        </div>
                        <div class="record-term">
                          <div>
                                <input type="text" class="input-primary" placeholder="Hash" name="hash" value="<?php echo $data['hash'] ?>">
                                <input type="text" class="input-primary" placeholder="钱包地址或标签" name="address" value="<?php echo $data['address'] ?>">
                          </div>
                          <div>
                            <button class="btn btn-primary">搜索</button>
                          </div>
                        </div>
                  </form>
              </div>
              <div class="container">
                    <div class="page-title" >钱包流水</div>
                    <div class="pagr-title-right">
                       
                         <?php if($data['coin_id'] != ""){ ?>
                          <div class="out-coin-total">
                             <span>
                               <?php echo $data['coin_symbol'] ?>约合：<?php if($data['allamount']){echo $data['allamount'];}else{echo 0;} ?>
                            </span>
                            <span>
                               矿工费约合：<?php if($data['allamount']){echo $data['fee'];}else{echo 0;} ?>
                            </span>
                          </div>
                        <?php } ?>
                      
                       
                         <?php if(strpos($data['permission'],',flow_do,') != false || $data['is_super'] == 1 || $data['is_power'] == 1){ ?>
                          <div class="out-coin-action">
                             <a href="/<?php echo $pro_no; ?>/walletflow/toExcel?coin_id=<?php echo $data['coin_id'] ?>&hash=<?php echo $data['hash'] ?>&address=<?php echo $data['address'] ?>&flow_type=<?php echo $data['flow_type'] ?>&obj_id=<?php echo $data['obj_id'] ?>&status=<?php echo $data['status'] ?>&begin_date=<?php echo $data['begin_date'] ?>&end_date=<?php echo $data['end_date'] ?>"><button class="btn btn-primary">导出Excel</button></a>
                          </div>
                        <?php } ?>
                   
                    </div>
                <div class="wallet-record-table">
                  <div class="table">
                    <table>
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>币种</th>
                          <th>金额</th>
                          <th>矿工费</th>
                          <th>出账地址</th>
                          <th>收款地址</th>
                          <th>Hash</th>
                          <th>类型</th>
                          <th>状态</th>
                          <th>操作时间</th>
                        </tr>
                      </thead>
                      <tbody>
                      <?php foreach($list as $v){ ?>
                          <tr>
                              <td><?php echo $v['id'];?></td>
                              <td><?php echo $v['coin_symbol'];?></td>
                              <td><?php echo $v['coin_amount'];?></td>
                              <td><?php echo $v['coin_chain_amount'];?></td>
                              <td>
                                  <p style="word-wrap: break-word;width: 200px;">
                                      <?php
                                      //                                  if($v['flow_type'] == 1){
                                      //                                      echo $v['to_address'];
                                      //                                  }else{
                                      //                                      echo $v['from_address'];
                                      //                                  }
                                      echo $v['from_address'];
                                      ?>
                                  </p>

                              </td>
                              <td>
                                  <p style="word-wrap: break-word;width: 200px;">
                                    <?php echo $v['to_address'];?>
                                  </p>
                              </td>
                              <td>
                                  <p style="word-wrap: break-word;width: 200px;">
                                      <?php if($data['coin_id'] != ''){ ?>

                                          <a href="<?php echo $data['blockchain'];?><?php echo $v['hash'];?>" target="_blank">
                                              <?php echo $v['hash'];?>
                                          </a>
                                      <?php }else{
                                          echo $v['hash'];
                                      } ?>
                                  </p>
                              </td>
                              <td>
                                  <?php
                                    if($v['flow_type'] == 1){
                                        echo "收入";
                                    }elseif($v['flow_type'] == 0){
                                        echo "支出";
                                    }
                                  ?>
                              </td>
                              <td>
                                  <?php
                                      if($v['status'] == 1) {
                                          echo '正常';
                                      }elseif($v['status'] == 0) {
                                  ?>
                                      <span style="color: red;"><?php echo "失败"; ?></span>
                                  <?php  } ?>
                              </td>
                              <td><?php echo date('Y-m-d,H:i:s',$v['updated_at'])?></td>
                          </tr>
                      <?php } ?>
                      </tbody>
                    </table>
                    <div class="pagination-box">
                        <?php
                        if($list){
                            //存储页码字符串
                            $pageNumString = "<div style='margin-top: 10px' class='pagination'>";
                            //当前页码数，默认当前页码为1
                            $curPage = isset($_GET['page'])?$_GET['page']:1;
                            if($curPage <=5){
                                $begin =1;
                                $end = $data['totalpage']>=10?10:$data['totalpage'];
                            }else{
                                $end = $curPage +5>$data['totalpage']?$data['totalpage']:$curPage +5;
                                $begin =$end -9<=1?1:$end -9;
                            }
                            //实现上一页
                            $prev = $data['page'] -1<=1?1:$data['page'] -1;
                            $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page=1">首页</a></li>';
                            $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.($prev).'">&laquo;</a></li>';

                            //根据起始页与终止页将当前页面的页码显示出来
                            for($i=$begin;$i<=$end;$i++){
                                //使用if实现高亮显示当前点击的页码
                                if($data['page'] == $i){
                                    $pageNumString .= '<li  class="active" style="float: left;"><a  href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                }else{
                                    $pageNumString .= '<li style="float: left;"><a href="?'.$data['search'].'page='.$i.'">'.$i.'</a></li>';
                                }
                            }


                            //实现下一页
                            $next = $data['page'] +1 >=$data['totalpage']?$data['totalpage']:$data['page'] +1;
                            $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$next.'">&raquo;</a></li>';
                            $pageNumString .='<li style="float: left;"><a href="?'.$data['search'].'page='.$data['totalpage'].'">尾页</a></li>';
                            $pageNumString .='</div>';
                            echo $pageNumString;
                        }

                        ?>
                    </div>
                  </div>
                </div>
              </div>
          </div>
      </div>
  </div>
<script type="text/javascript" src="/static/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/static/js/moment.min.js"></script>
<script type="text/javascript" src="/static/js/datepicker.all.js"></script>
<script type="text/javascript" src="/static/js/inexwalletadmin.js"></script>
<script>
    $(document).ready(function(){
         chooseTime()
    })
</script>
</body>
</html>